// Value Cloud Benefit Stories - General Enablement Data
// One universal story per benefit — designed for sales/CSM quick reference

export type Solution = 'itsm' | 'uem' | 'security' | 'esm' | 'general';

export type BenefitStory = {
  id: string;
  benefitName: string;
  solution: Solution;
  category: 'financial' | 'time-savings';
  subcategory: string;
  description: string;
  formula: string;
  formulaFactors: string[];
  scenario: string;
  talkTrack: string;
  whyItMatters: string;
  exampleMetric: string;
  tips: string[];
};

export const benefits: BenefitStory[] = [
  // ═══════════════════════════════════════════
  // ITSM BENEFITS
  // ═══════════════════════════════════════════
  {
    id: 'high-priority-ticket-routing',
    benefitName: 'High Priority Ticket Routing',
    solution: 'itsm',
    category: 'financial',
    subcategory: 'Penalties & Fines Avoidance',
    description: 'Neurons for ITSM routes high-priority tickets to the right teams without delay. By leveraging workflows and contextual data, it ensures urgent issues are escalated and addressed quickly, reducing compliance penalty exposure and improving service reliability.',
    formula: 'Annual Compliance Penalty Exposure × % Improvement with Automation & Workflows × Benefit Ramp',
    formulaFactors: ['Annual compliance penalty exposure', 'Improvement with automation & workflows (default: 20%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] has a critical incident affecting a production system. The ticket gets logged but sits in a general queue for 40+ minutes before someone realizes it\'s a high-severity issue. By then, the SLA clock has been ticking and downstream business impact is growing.',
    talkTrack: 'When a critical incident comes in, every minute it sits in the wrong queue is a minute closer to an SLA breach or a compliance violation. Automated priority routing reads the ticket context — severity, affected system, business impact — and puts it directly in front of the right team. No triage delay, no misclassification. The 20% improvement means 1 in 5 potential SLA breaches gets caught by routing before it becomes a real problem.',
    whyItMatters: 'Misrouted critical tickets don\'t just cost penalty dollars — they erode trust with the business and can cause cascading failures. Smart routing is the difference between a contained incident and a company-wide fire drill.',
    exampleMetric: 'If [Company] has $250K in annual compliance penalty exposure, a 20% improvement = $50K in avoided penalties per year.',
    tips: [
      'Ask about their SLA structure — the more tiers they have, the more routing matters',
      'Healthcare and finance have the highest penalty exposure — lean into regulatory risk',
      'Ask: "What happens today when a P1 ticket gets misclassified as a P3?"',
    ],
  },
  {
    id: 'reduced-incident-aht',
    benefitName: 'Reduced Incident Average Handle Time (AHT)',
    solution: 'itsm',
    category: 'financial',
    subcategory: 'Operational Efficiencies',
    description: 'Neurons for ITSM provides process optimization tools such as quick actions, knowledgebase articles, and automated workflows to lower incident average handle time. These enable agents to resolve issues more quickly and efficiently.',
    formula: 'Annual Tickets × % Reduction in AHT × AHT Cost per Incident × Benefit Ramp',
    formulaFactors: ['Annual Tickets', 'Reduction in AHT (default: 11%)', 'AHT cost per incident', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] service desk agents spend 10+ minutes per ticket on context gathering — figuring out what environment they\'re dealing with, what tools apply, and what the resolution history looks like — before they even start troubleshooting.',
    talkTrack: 'Your agents are spending a big chunk of every ticket just getting oriented — who is this user, what device, what happened before? With auto-categorization and suggested resolutions based on context, you eliminate that lookup time. Instead of 10 minutes of investigation, the agent gets a pre-loaded context card with the right workflow. That shaves 3-4 minutes off every interaction — and across tens of thousands of tickets, that\'s real capacity back.',
    whyItMatters: 'AHT reduction is the purest efficiency metric. If you can reduce handle time by 11%, you\'re either serving the same volume with fewer people, or absorbing growth without adding headcount. It directly protects operational margins.',
    exampleMetric: 'At 60,000 tickets/year with $26 cost per ticket, an 11% AHT reduction = $171.6K in annual savings.',
    tips: [
      'Ask about their current AHT — most orgs know this number and it\'s a great conversation starter',
      'Frame it as "capacity back" not "headcount reduction" — nobody wants to hear they\'re losing jobs',
      'Multiply the per-ticket savings by annual volume to show the scale',
    ],
  },
  {
    id: 'optimized-knowledge',
    benefitName: 'Optimized Knowledge for Improved Service Delivery',
    solution: 'itsm',
    category: 'financial',
    subcategory: 'Operational Efficiencies',
    description: 'Neurons for ITSM provides employees with easy access to self-service portals and searchable knowledge base articles, helping them resolve common issues without submitting support tickets.',
    formula: 'Annual Tickets × % Improved Productivity with KB Optimization × AHT Cost per Incident × Benefit Ramp',
    formulaFactors: ['Annual Tickets', 'Improved productivity with KB optimization (default: 10%)', 'AHT cost per incident', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] gets the same 15 questions submitted as tickets every week — password policies, VPN setup, software access requests. The answers exist somewhere in a buried SharePoint folder that nobody can find. Each repetitive ticket costs the same as a unique one.',
    talkTrack: 'How many of your tickets are the same question asked for the 400th time? "How do I connect to VPN?" "Where do I submit an expense report?" With optimized knowledge, a searchable self-service portal surfaces the answer instantly — before the user even submits a ticket. That 10% deflection means your agents focus on real problems instead of being a human FAQ.',
    whyItMatters: 'Knowledge deflection is the only way to scale support without scaling headcount. Every ticket deflected is capacity returned. And it\'s better for the user too — they get their answer in 2 minutes instead of waiting 4 hours for a ticket response.',
    exampleMetric: 'At 60,000 tickets/year with $26 cost per ticket, a 10% knowledge deflection = $156K in annual savings.',
    tips: [
      'Ask: "What percentage of your tickets are repetitive or have a known answer?"',
      'Most orgs underestimate this — it\'s usually 30-40% of volume',
      'Frame it as employee experience improvement, not just IT efficiency',
    ],
  },
  {
    id: 'self-service-ticket-deflection',
    benefitName: 'Self-Service Portal Ticket Deflection',
    solution: 'itsm',
    category: 'financial',
    subcategory: 'Operational Efficiencies',
    description: 'Neurons for ITSM empowers employees to resolve or request assistance through automated business processes and self-service environments, reducing the volume of tickets that require agent intervention.',
    formula: 'Annual Tickets × % Self-Service Deflection Rate × Average Ticket Cost × Benefit Ramp',
    formulaFactors: ['Annual Tickets', 'Self-service deflection rate (default: 15%)', 'Average ticket cost', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] employees submit tickets for things like software access requests, password resets, and hardware requests — all of which could be fulfilled through a self-service catalog with automated workflows. Instead, agents manually process each one.',
    talkTrack: 'A significant portion of your ticket volume comes from requests that have standardized fulfillment steps — software installs, access requests, hardware orders. When you stand up a self-service portal with an automated catalog, employees can request what they need, approvals route automatically, and fulfillment happens without an agent touching it. The key is making self-service easy enough that people actually use it.',
    whyItMatters: 'Self-service deflection reduces agent workload while improving the employee experience — they get what they need faster without waiting in a ticket queue. It\'s a win-win that scales naturally as the organization grows.',
    exampleMetric: 'At 60,000 tickets/year with $26 cost per ticket, a 15% deflection = $234K in annual savings.',
    tips: [
      'Ask about their current self-service adoption rate — most are under 20%',
      'Emphasize the employee experience angle: faster resolution, no waiting',
      'Service catalog with automated fulfillment is the hook — not just a portal',
    ],
  },
  {
    id: 'reduced-escalation-rate',
    benefitName: 'Reduced Escalation Rate (L1→L2→L3)',
    solution: 'itsm',
    category: 'financial',
    subcategory: 'Operational Efficiencies',
    description: 'Neurons for ITSM enables better first-contact resolution through AI-assisted suggestions, knowledge surfacing, and improved ticket context — reducing the rate of costly escalations from L1 to L2 and L3 support teams.',
    formula: 'Escalated Tickets × Cost Differential (L2/L3 vs L1) × % Reduction in Escalation Rate × Benefit Ramp',
    formulaFactors: ['Number of escalated tickets', 'Cost differential between support tiers', 'Reduction in escalation rate (default: 12%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] escalates 35% of tickets from L1 to L2/L3 because agents lack the context or tools to resolve at first contact. Each escalation costs 3-4x more than an L1 resolution and adds hours to the resolution time.',
    talkTrack: 'Every time a ticket escalates from L1 to L2, it costs you 3-4x more — the L2 engineer is more expensive, they have to re-read the ticket, and the user waits longer. With AI-assisted suggestions and better knowledge surfacing, your L1 agents resolve issues they would have previously escalated. A 12% reduction in escalation rate means thousands of tickets stay at the cheapest resolution tier.',
    whyItMatters: 'Escalation is the silent cost killer in service desk operations. Most orgs know their L1 cost per ticket but don\'t realize their effective cost is much higher because of escalation rates. Keeping tickets at L1 is the fastest path to cost control.',
    exampleMetric: 'If 35% of 60,000 tickets escalate (21,000), reducing that by 12% keeps 2,520 tickets at L1 — saving $150-250K annually depending on tier cost differential.',
    tips: [
      'Ask for their current escalation rate — anything above 25% is a strong conversation',
      'Calculate the cost differential between L1 ($26) and L2/L3 ($80-120) to show the multiplier',
      'AI-assisted resolution suggestions are the key capability to highlight',
    ],
  },
  {
    id: 'improved-mttr',
    benefitName: 'Improved Mean Time to Resolution (MTTR)',
    solution: 'itsm',
    category: 'time-savings',
    subcategory: 'Productivity Recovery',
    description: 'Neurons for ITSM reduces overall Mean Time to Resolution by combining better routing, knowledge access, automation, and incident correlation — recovering employee productivity lost to IT issues.',
    formula: 'Addressable Employee Downtime Hours × % MTTR Improvement × Revenue Impact per FTE per Hour × Benefit Ramp',
    formulaFactors: ['Addressable employee downtime hours', 'MTTR improvement (default: 10%)', 'Revenue impact per FTE per hour', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] employees lose an average of 6.5 hours per year waiting for IT issues to be resolved. Across thousands of employees, that\'s tens of thousands of hours of lost productivity sitting idle while tickets work through the system.',
    talkTrack: 'Every hour an employee spends waiting on IT is an hour they\'re not productive. We reduce that wait time through better incident routing — tickets go to the right team faster — SLA enforcement, and self-service options. A 10% improvement in MTTR across your employee base recovers thousands of productive hours. That\'s not IT efficiency — that\'s business productivity.',
    whyItMatters: 'MTTR is the metric the business cares about. Your CFO doesn\'t think about AHT — they think about how many hours their people are sitting idle because of IT. Framing the value as recovered business productivity connects IT improvement to business outcomes.',
    exampleMetric: 'At 33,000 hours of addressable downtime and $120/hr revenue impact, a 10% MTTR improvement = $396K in recovered productivity.',
    tips: [
      'Use revenue impact per FTE per hour ($120 default) — it resonates with executives',
      'Frame as "hours recovered for the business" not "IT tickets resolved faster"',
      'Ask: "How much time do your employees spend waiting on IT per month?"',
    ],
  },
  {
    id: 'automated-change-management',
    benefitName: 'Automated Change Management Efficiency',
    solution: 'itsm',
    category: 'financial',
    subcategory: 'Operational Efficiencies',
    description: 'Neurons for ITSM streamlines the change management process through CMDB-informed impact analysis, dynamic approval policies, and automated workflows — reducing change-related outages and improving change success rate.',
    formula: 'Annual Outages × % Reduction in Outage Impacts × Lost Productivity per Outage × Benefit Ramp',
    formulaFactors: ['Annual outages (default: 3.96)', '% reduction in outage impacts (default: 20%)', 'Lost productivity per outage', 'Benefit Ramp (default: 60/100/100%)'],
    scenario: '[Company] experiences ~4 outages per year caused by changes that had unintended downstream effects. Each outage costs tens of thousands in lost productivity because the change team couldn\'t see what depended on the system being changed.',
    talkTrack: 'One of the most common causes of service disruptions is changes that have unintended downstream effects. When your change management process has a CMDB that shows exactly what\'s connected to what, you can see the potential blast radius before you approve. Dynamic approval policies route changes to the right reviewers based on risk. The goal is fewer surprises when changes go live.',
    whyItMatters: 'Change-related outages are preventable. Every outage caused by a poorly assessed change is a failure of process, not technology. Giving your change team dependency visibility is one of the highest-ROI improvements you can make.',
    exampleMetric: 'At ~4 outages/year and $43K lost productivity per outage, a 20% reduction = $34.2K in avoided downtime costs.',
    tips: [
      'Ask: "What percentage of your outages are caused by changes?" — most orgs say 40-60%',
      'The CMDB connection is the key differentiator — impact analysis before the change happens',
      'Ramp starts at 60% Y1 because change process maturity takes time',
    ],
  },
  {
    id: 'proactive-problem-management',
    benefitName: 'Proactive Problem Management',
    solution: 'itsm',
    category: 'financial',
    subcategory: 'Incident Prevention',
    description: 'Neurons for ITSM enables proactive identification of recurring incident patterns and root causes, preventing repeat incidents before they impact users and reducing overall incident volume.',
    formula: 'Recurring Incident Volume × Average Incident Cost × % Reduction Through Problem Management × Benefit Ramp',
    formulaFactors: ['Recurring incident volume', 'Average incident cost', 'Reduction through proactive problem management (default: 15%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] sees the same 10 incidents repeat every month — the same app crashes, the same printer fails, the same VPN disconnects. Each time it\'s treated as a new incident instead of addressing the underlying problem. The IT team is stuck in firefighting mode.',
    talkTrack: 'How many of your incidents are repeat offenders? The same app crash, the same printer failure, the same VPN drop — over and over. Problem management shifts from firefighting to prevention. You identify the pattern, find the root cause, fix it once, and eliminate an entire category of incidents. A 15% reduction in recurring incidents means your team spends less time fighting the same fires and more time on strategic work.',
    whyItMatters: 'Reactive incident management is an infinite treadmill. Problem management is how you get off it. Every root cause you fix permanently eliminates a category of incidents — that\'s compounding value over time.',
    exampleMetric: 'If 30% of 60,000 tickets are recurring (18,000), a 15% reduction through problem management eliminates 2,700 tickets annually.',
    tips: [
      'Ask for their top 10 recurring incidents — this makes the value tangible immediately',
      'Frame problem management as "fix it once, stop fighting it forever"',
      'Most orgs skip problem management because they\'re too busy with incidents — that\'s the trap',
    ],
  },

  // ═══════════════════════════════════════════
  // ESM / LOB BENEFITS
  // ═══════════════════════════════════════════
  {
    id: 'asset-relationship-management',
    benefitName: 'Asset Relationship Management',
    solution: 'esm',
    category: 'financial',
    subcategory: 'Operational Efficiencies',
    description: 'Neurons for ITSM delivers visibility into assets and their associated users, enabling IT teams to manage relationships more effectively. By linking assets to user profiles, it accelerates issue resolution and improves lifecycle management.',
    formula: 'IT FTEs Dedicated to SAM & HAM × % Reduction in Effort × Fully Loaded IT FTE Annual Salary × Benefit Ramp',
    formulaFactors: ['IT FTEs dedicated to SAM & HAM', 'Reduction in effort (default: 2%)', 'Fully loaded IT FTE Annual Salary', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] needs to answer "how many devices are running outdated OS versions?" but the asset team spends days pulling data from multiple sources and reconciling spreadsheets. When an audit comes, they discover 5-10% discrepancies between their records and reality.',
    talkTrack: 'When someone asks "what devices does this user have?" or "which assets are running end-of-life software?" — how long does it take your team to answer? Automated asset relationships link every device to its user, location, and compliance status. Your annual audit prep goes from weeks of reconciliation to a same-day export. The 2% effort reduction is the steady state, but the real value is instant answers when leadership or auditors ask.',
    whyItMatters: 'Asset management accuracy directly impacts every other IT function — security, compliance, procurement, support. If your asset data is wrong, decisions built on it are wrong. Automated relationships are the foundation.',
    exampleMetric: 'With 10 FTEs on SAM/HAM at $89K loaded cost, 2% effort reduction = $17.8K in direct savings plus dramatically faster audit response.',
    tips: [
      'Ask: "How long does it take to produce a complete asset inventory for an audit?"',
      'The 2% number sounds small — emphasize the audit readiness and decision quality angle',
      'Connect asset accuracy to security posture: "You can\'t protect what you can\'t see"',
    ],
  },
  {
    id: 'energy-utility-cost-optimisation',
    benefitName: 'Energy & Utility Cost Optimisation Through Data-Driven Operations',
    solution: 'esm',
    category: 'financial',
    subcategory: 'Facilities Management',
    description: 'Neurons for FM supports energy optimization by consolidating operational data, monitoring system performance, and providing actionable insights that reduce waste.',
    formula: 'FM Annual Utilities Cost × Data-Driven Efficiency Improvement (%) × Benefit Ramp',
    formulaFactors: ['FM annual utilities cost (default: $6,190,000)', 'Data-driven efficiency improvement (default: 5.6%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] has multiple facilities with HVAC systems running independently, lights left on in unoccupied spaces, and no visibility into which locations are driving the annual utility bill. Energy costs keep rising with no way to identify the waste.',
    talkTrack: 'When you\'re managing millions in facilities spend across multiple locations, you need visibility. Neurons for FM consolidates data from all your buildings — HVAC performance, occupancy sensors, lighting systems — and shows you exactly where energy is being wasted. That 5.6% efficiency improvement comes from catching the buildings running heat and AC simultaneously, the lights on in empty spaces, and the equipment running after hours.',
    whyItMatters: 'Facilities costs are a major operational expense that most organizations treat as fixed. Data-driven optimization turns it into a managed, measurable operation with real savings that drop straight to the bottom line.',
    exampleMetric: 'At $6.19M annual utilities cost, a 5.6% improvement = $346,600 in annual energy savings.',
    tips: [
      'Ask about their total annual facilities/utility spend — most executives know this number',
      'Sustainability goals make this resonate at the C-level, not just facilities',
      'Even modest percentage improvements on large utility budgets = big dollar savings',
    ],
  },
  {
    id: 'vendor-contract-insights',
    benefitName: 'Vendor Contract Insights',
    solution: 'esm',
    category: 'financial',
    subcategory: 'IT Asset Management',
    description: 'Neurons for ITAM helps IT teams evaluate vendor contracts and renegotiate terms to align with actual usage. Expiring contracts are flagged for review, preventing auto-renewals on unfavorable terms.',
    formula: 'Annual Vendor Contract Exposure × Reduction in IT Overspend (%) × Benefit Ramp',
    formulaFactors: ['Annual vendor contract exposure (default: $200,000)', 'Reduction in IT overspend (default: 25%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] has software licenses for 500 users but only 320 are actively using the application. Maintenance renewals auto-renew annually at full price because nobody reviews usage before the renewal date.',
    talkTrack: 'How many of your software contracts auto-renew without anyone checking if you\'re still using what you\'re paying for? ITAM with contract insights shows you actual usage versus licensed capacity, flags contracts 90 days before renewal so you can negotiate, and identifies where you\'re over-licensed. That 25% reduction comes from right-sizing, negotiating from data, and preventing auto-renewals on unfavorable terms.',
    whyItMatters: 'Contract drift is a silent budget killer. Auto-renewals, shelfware, and over-licensing quietly consume IT budget that could be redirected to strategic initiatives. Visibility is leverage.',
    exampleMetric: 'At $200K annual contract exposure, a 25% reduction in overspend = $50K in annual savings.',
    tips: [
      'Ask: "When was the last time you reviewed all your software licenses before renewal?"',
      'Most orgs have 15-25% shelfware — software they pay for but nobody uses',
      'The auto-renewal prevention angle is powerful: "How many contracts auto-renewed last year?"',
    ],
  },
  {
    id: 'improve-maintenance-efficiency',
    benefitName: 'Improve Maintenance Efficiency via Predictive & Preventative Capabilities',
    solution: 'esm',
    category: 'financial',
    subcategory: 'Facilities Management',
    description: 'Neurons for FM enables facilities teams to shift from reactive to predictive maintenance, reducing emergency repairs and extending equipment life through data-driven maintenance scheduling.',
    formula: 'FM Maintenance Staff FTEs × Fully Loaded Salary × % Efficiency Improvement × Benefit Ramp',
    formulaFactors: ['FM Maintenance Staff FTEs (default: 60)', 'FM Maintenance Fully Loaded Salary (default: $80,776)', 'Efficiency improvement (default: 3.6%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] maintenance team spends 40% of their time on emergency repairs — fixing things that broke unexpectedly. Each emergency costs 3-5x more than a planned repair because of overtime, expedited parts, and business disruption.',
    talkTrack: 'When your maintenance team is in constant firefighting mode, they can\'t do the planned work that prevents the next emergency. Predictive capabilities help them prioritize based on actual equipment condition — which units are degrading, which need attention this quarter, which can wait. That shift from reactive to predictive means fewer emergencies, lower repair costs, and equipment that lasts longer.',
    whyItMatters: 'Emergency maintenance costs 3-5x more than planned maintenance. Every emergency repair you prevent is a multiplied savings. Plus, equipment that\'s maintained proactively lasts longer — reducing capital replacement costs.',
    exampleMetric: 'With 60 maintenance staff at $80.8K loaded salary, a 3.6% efficiency improvement = $173.4K in annual savings.',
    tips: [
      'Ask about their ratio of planned vs. unplanned maintenance — below 60% planned is a red flag',
      'Frame as "shifting from firefighting to prevention"',
      'Capital avoidance from extended equipment life is often larger than the labor savings',
    ],
  },
  {
    id: 'automated-compliance-management',
    benefitName: 'Automated & Integrated Compliance Management',
    solution: 'esm',
    category: 'financial',
    subcategory: 'Governance, Risk & Compliance',
    description: 'Neurons for GRC automates compliance evidence gathering, assessment tracking, and reporting — reducing the manual effort required to maintain and demonstrate regulatory compliance.',
    formula: 'Compliance & Audit Staff FTEs × Fully Loaded Salary × % Efficiency Improvement × Benefit Ramp',
    formulaFactors: ['Compliance Staff FTEs (default: 12)', 'Audit Staff FTEs (default: 6)', 'Fully loaded salaries', 'Efficiency improvement (default: 15%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] compliance team spends 60% of their time manually gathering evidence, filling out assessments, and compiling reports for audits. They\'re highly paid professionals doing data entry work instead of actual risk management.',
    talkTrack: 'Your compliance team is expensive — $114K fully loaded per person. If they\'re spending 60% of their time on manual evidence gathering and report compilation, that\'s a massive waste of specialized talent. GRC automates the tedious parts — evidence collection, assessment tracking, report generation — so your compliance team focuses on actual risk management and strategic guidance.',
    whyItMatters: 'Compliance isn\'t going away — it\'s growing. Manual compliance processes don\'t scale with regulatory complexity. Automation is the only way to handle increasing compliance requirements without proportionally increasing headcount.',
    exampleMetric: 'With 12 compliance staff ($114.4K) and 6 audit staff, a 15% efficiency improvement = $233.4K in annual savings.',
    tips: [
      'Ask: "How many audits/assessments does your team manage per year?"',
      'Frame automation as freeing experts for risk analysis, not replacing them',
      'Regulated industries (banking, healthcare, energy) have the strongest pain here',
    ],
  },
  {
    id: 'streamline-onboarding',
    benefitName: 'Streamline Employee Onboarding & Transitions',
    solution: 'esm',
    category: 'financial',
    subcategory: 'HR Service Management',
    description: 'Neurons for HRSM automates the entire employee lifecycle — from day-zero provisioning through role transitions to offboarding — coordinating across IT, HR, and department workflows.',
    formula: 'HRSM Staff FTEs × Fully Loaded Salary × % Efficiency Improvement × Benefit Ramp',
    formulaFactors: ['HRSM Staff FTEs (default: 20)', 'HRSM Fully Loaded Salary (default: $103,886)', 'Efficiency improvement (default: 3.6%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] onboards 500 new employees per year. Each new hire touches IT, HR, facilities, and 2-3 department leads. Most of the coordination is manual — emails, spreadsheets, and a lot of "did anyone set up their access yet?" follow-ups.',
    talkTrack: 'Onboarding a new employee today touches IT, HR, facilities, and multiple department leads. Most of the coordination is manual — emails back and forth, spreadsheets tracking who did what, and inevitably someone falls through the cracks. With automated workflows, each step triggers the next automatically. HR approves, IT provisions, facilities assigns a desk, security grants access — all coordinated without someone chasing each step.',
    whyItMatters: 'Slow onboarding means new hires aren\'t productive for days or weeks. Fast, automated onboarding means they\'re contributing from day one. And the offboarding side matters for security — every day a departed employee retains access is a risk.',
    exampleMetric: 'With 20 HRSM staff at $103.9K loaded salary, a 3.6% efficiency improvement = $75K in annual savings.',
    tips: [
      'Ask: "How many days does it take to fully provision a new hire?"',
      'The security angle on offboarding is powerful: "How quickly do you revoke access when someone leaves?"',
      'High-turnover industries (retail, hospitality) feel this pain acutely',
    ],
  },
  {
    id: 'improve-project-delivery',
    benefitName: 'Improve Project Delivery Predictability',
    solution: 'esm',
    category: 'financial',
    subcategory: 'Project & Portfolio Management',
    description: 'Neurons for PPM provides real-time dashboards, resource forecasting, and automated status updates so projects stay on track and stakeholders have visibility without manual reporting.',
    formula: 'PMO Staff FTEs × Fully Loaded Salary × % Productivity Improvement × Benefit Ramp',
    formulaFactors: ['PMO Staff FTEs (default: 15)', 'PMO Fully Loaded Salary (default: $100,750)', 'Productivity improvement (default: 6%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] PMO team spends 30% of their time on manual status reporting — collecting updates from project managers, compiling dashboards, reconciling resource plans. Leadership gets a picture that\'s already a week old by the time they see it.',
    talkTrack: 'Your PMO team\'s job is to ensure projects deliver on time and on budget. But if they\'re spending 30% of their time compiling status reports and chasing project managers for updates, they\'re not actually managing projects — they\'re managing spreadsheets. PPM automates the reporting so your PMO team focuses on the work that matters: risk identification, resource optimization, and stakeholder management.',
    whyItMatters: 'Project delays are expensive — every week a project slips costs money in delayed value realization and idle resources. Better project visibility means earlier intervention on at-risk projects.',
    exampleMetric: 'With 15 PMO staff at $100.8K loaded salary, a 6% productivity improvement = $90.7K in annual savings.',
    tips: [
      'Ask: "What percentage of your projects deliver on time and on budget?"',
      'Frame as visibility and early warning, not micromanagement',
      'Connect delayed projects to delayed business value — that resonates with executives',
    ],
  },
  {
    id: 'smarter-portfolio-decisions',
    benefitName: 'Make Smarter Portfolio Investment Decisions',
    solution: 'esm',
    category: 'financial',
    subcategory: 'Project & Portfolio Management',
    description: 'Neurons for PPM gives leadership data-driven portfolio visibility — which projects to fund, which to cut, and where resources deliver maximum impact.',
    formula: 'PMO Staff FTEs × Fully Loaded Salary × % Better Resource Allocation × Benefit Ramp',
    formulaFactors: ['PMO Staff FTEs (default: 15)', 'PMO Fully Loaded Salary (default: $100,750)', 'Better resource allocation (default: 4%)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] runs 50+ projects simultaneously but leadership can\'t easily see which ones are delivering value and which are burning resources. Investment decisions are based on who presents the best PowerPoint, not actual data.',
    talkTrack: 'Portfolio decisions should be data-driven, not politics-driven. PPM gives leadership a real-time view of every project\'s health, resource consumption, and expected value delivery. When it\'s time to decide where to invest next quarter\'s budget, you have the data to back the decision — not just the loudest voice in the room.',
    whyItMatters: 'Bad portfolio decisions compound. Funding the wrong project doesn\'t just waste that project\'s budget — it starves the right projects of resources. Data-driven portfolio management is a force multiplier for the entire organization.',
    exampleMetric: 'With 15 PMO staff at $100.8K loaded salary, a 4% improvement in resource allocation = $60.5K in annual savings.',
    tips: [
      'This resonates most with CIOs and CFOs — they own the portfolio decisions',
      'Ask: "How do you decide which projects get funded?"',
      'Frame as "investing in the right projects" not "cutting the wrong ones"',
    ],
  },

  // ═══════════════════════════════════════════
  // UEM BENEFITS
  // ═══════════════════════════════════════════
  {
    id: 'reduced-energy-consumption',
    benefitName: 'Reduced Energy Consumption',
    solution: 'uem',
    category: 'financial',
    subcategory: 'IT Asset Management',
    description: 'Neurons for ITAM helps identify idle, end-of-life, or underutilized devices that should be powered down, decommissioned, or consolidated — reducing the organization\'s energy footprint.',
    formula: 'Endpoint Devices × Energy Cost per Device × % Reduction through Lifecycle Management × Benefit Ramp',
    formulaFactors: ['Number of endpoint devices (default: 10,000)', 'Energy cost per device', 'Reduction through lifecycle management', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] has 10,000 endpoints but no clear picture of how many are idle, forgotten, or running unnecessarily. Devices in storage rooms still draw power. Decommissioned machines sit powered on for months.',
    talkTrack: 'How many devices in your environment are powered on right now that nobody is using? Old machines in closets, decommissioned laptops still plugged in, test devices that were never shut down. ITAM identifies those devices so you can decommission or power them down. The savings per device are small, but across thousands of endpoints, it adds up — and it supports your sustainability goals.',
    whyItMatters: 'Energy reduction is a straightforward cost savings that also supports ESG and sustainability commitments. It\'s an easy win that nobody argues against.',
    exampleMetric: 'With 10,000 endpoints, identifying and decommissioning idle devices saves approximately $4.5K per year in energy costs.',
    tips: [
      'Small dollar amount — bundle this with other ITAM benefits for a stronger story',
      'The sustainability/ESG angle can elevate this benefit to C-suite visibility',
      'Ask: "How do you handle decommissioning — is there a defined process?"',
    ],
  },
  {
    id: 'reduced-hardware-maintenance',
    benefitName: 'Reduced Hardware Maintenance Costs',
    solution: 'uem',
    category: 'financial',
    subcategory: 'IT Asset Management',
    description: 'Neurons for ITAM enables organizations to optimize hardware maintenance contracts by providing accurate data on warranty status, equipment age, and utilization — eliminating overpayment for unnecessary coverage.',
    formula: 'Endpoint Devices × Average Maintenance Cost × % Reduction through Contract Optimization × Benefit Ramp',
    formulaFactors: ['Number of endpoint devices (default: 10,000)', 'Average maintenance cost per device', 'Reduction through optimized contracts', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] pays maintenance contracts on all 10,000 devices but many are under manufacturer warranty, some are end-of-life (should be replaced, not maintained), and some have coverage levels that exceed their criticality.',
    talkTrack: 'When you know exactly what hardware you have, its age, warranty status, and criticality, you can negotiate smarter maintenance contracts. Stop paying maintenance on devices still under manufacturer warranty. Stop paying premium coverage on non-critical devices. Retire end-of-life equipment instead of renewing maintenance. That data-driven approach saves about $50K per year.',
    whyItMatters: 'Maintenance contracts are a "set it and forget it" expense that quietly grows. ITAM visibility turns it into a managed, optimized cost line.',
    exampleMetric: 'With 10,000 devices, optimizing maintenance contracts saves approximately $50K per year.',
    tips: [
      'Ask: "When was the last time you reviewed your hardware maintenance contracts?"',
      'The warranty overlap angle is powerful — paying for coverage the manufacturer already provides',
      'Connect to asset lifecycle: right-sizing maintenance is part of good lifecycle management',
    ],
  },
  {
    id: 'smarter-device-insights',
    benefitName: 'Smarter Device Insights',
    solution: 'uem',
    category: 'financial',
    subcategory: 'Digital Workspace',
    description: 'Neurons Workspace provides IT with detailed device analytics that inform smarter decisions about device refresh, configuration, and support — reducing unnecessary spending.',
    formula: 'Device Fleet × Insight-Driven Cost Avoidance × Benefit Ramp',
    formulaFactors: ['Device fleet size', 'Cost avoidance from better device decisions', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] refreshes devices on a fixed 3-year cycle regardless of condition. Some devices are in great shape at 3 years while others are struggling at 18 months. Without device health data, they replace everything on the same schedule.',
    talkTrack: 'Device refresh is one of your biggest recurring capital expenses. If you\'re replacing everything on a fixed cycle, you\'re over-spending on devices that are still healthy and under-spending on devices that are failing early. Workspace gives you the device health data to make smarter decisions — extend the life of healthy devices, prioritize replacement of struggling ones. Better data = better spending.',
    whyItMatters: 'Data-driven device decisions reduce both capital and operational costs. It\'s about spending the right amount in the right places, not just spending less.',
    exampleMetric: 'Improved device decision-making saves approximately $3.5K per year in avoided unnecessary spending.',
    tips: [
      'Small standalone number — bundle with other UEM benefits',
      'The device refresh cycle conversation is a strong entry point for UEM',
      'Ask: "What\'s your current device refresh cycle? Is it based on age or condition?"',
    ],
  },
  {
    id: 'automated-security-compliance',
    benefitName: 'Automated Security Compliance',
    solution: 'uem',
    category: 'financial',
    subcategory: 'Mobile Device Management',
    description: 'Neurons for MDM automates security compliance across the entire mobile device fleet — enforcing policies, pushing updates, and ensuring every device meets organizational security standards without manual intervention.',
    formula: 'Endpoint Devices × IT Staff Hours Saved × IT Hourly Rate × Benefit Ramp',
    formulaFactors: ['Number of endpoint/mobile devices', 'IT staff hours saved from automated compliance checks', 'IT hourly rate ($52)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] IT team manually checks device compliance weekly — verifying OS versions, encryption status, security patches. With 10,000 devices, this is a never-ending cycle that consumes thousands of IT hours per year.',
    talkTrack: 'Manually checking every mobile device for compliance doesn\'t scale. With 10,000 devices, by the time you finish checking the last one, the first one is out of compliance again. MDM automates those checks and enforces policies automatically — non-compliant device detected, policy pushed, compliance restored. Your security team stops chasing devices and starts focusing on real threats.',
    whyItMatters: 'Mobile device compliance is table stakes for security, but manual enforcement is a losing battle at scale. Automation is the only way to maintain consistent compliance across a growing device fleet.',
    exampleMetric: 'Automating compliance across 10,000 devices saves approximately $208K per year in IT staff time.',
    tips: [
      'Ask: "How do you verify mobile device compliance today?"',
      'The scale argument is powerful: "At 10,000 devices, manual compliance is impossible"',
      'BYOD environments amplify this benefit — more device diversity = more compliance complexity',
    ],
  },
  {
    id: 'reduced-it-support-costs',
    benefitName: 'Reduced IT Support Costs',
    solution: 'uem',
    category: 'financial',
    subcategory: 'Mobile Device Management',
    description: 'Neurons for MDM reduces device-related support tickets through remote troubleshooting, automated fixes, and self-service device management — lowering the cost of supporting mobile devices.',
    formula: 'Device-Related Tickets × Average Ticket Cost × % Reduction from Remote Management × Benefit Ramp',
    formulaFactors: ['Device-related ticket volume', 'Average ticket cost ($26)', 'Reduction from MDM capabilities', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] help desk gets thousands of device-related tickets per year — WiFi issues, app crashes, profile problems. Most require the user to bring the device to IT or ship it in, adding days of downtime for each issue.',
    talkTrack: 'A huge portion of your device tickets are things that could be fixed remotely — WiFi configuration, app reinstalls, profile issues, OS updates. MDM enables remote troubleshooting so your team can fix the device without the user ever leaving their desk. No more "bring it to IT" for routine issues. The result is fewer tickets, faster resolution, and less user downtime.',
    whyItMatters: 'Device support costs scale with device count and device diversity. As organizations add more device types and support BYOD, MDM is the only way to keep support costs from scaling linearly.',
    exampleMetric: 'Remote management and self-service capabilities reduce device support costs by approximately $468K per year.',
    tips: [
      'Ask: "What percentage of your tickets are device-related?"',
      'Remote fix capability is the key differentiator — no shipping devices, no desk visits',
      'BYOD support is increasingly demanded — MDM makes it manageable',
    ],
  },

  // ═══════════════════════════════════════════
  // SECURITY BENEFITS
  // ═══════════════════════════════════════════
  {
    id: 'reduce-exploitation-recovery-costs',
    benefitName: 'Reduce Exploitation Recovery Costs',
    solution: 'security',
    category: 'financial',
    subcategory: 'Risk & Security',
    description: 'Neurons for RBVM helps cut recovery costs by preventing exploitation through proactive vulnerability prioritization. Using threat intelligence and asset criticality, it focuses remediation on the most exploitable risks.',
    formula: 'Recovery Costs per Exploit × Annual Number of Exploits × % Reduction × Benefit Ramp',
    formulaFactors: ['Recovery costs per exploit (default: $40,000)', 'Annual exploits (default: 5)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] gets hit by an exploit that requires system rebuilds, data restoration, and incident response. The vulnerability had been in the backlog for 3 months but was never prioritized because the team was patching everything equally instead of by risk.',
    talkTrack: 'When an exploit hits, recovery is expensive — system rebuilds ($10K), data restoration ($30K), incident response ($25K) per event. The irony is the vulnerability was known — it just wasn\'t prioritized. RBVM uses threat intelligence to tell you: "this vulnerability is being actively exploited in the wild and it affects your critical systems — fix this one first." You patch what matters before the bad guys get there.',
    whyItMatters: 'The cost of recovery always exceeds the cost of prevention. Every exploit you prevent by patching the right vulnerability first is $40K+ in avoided recovery costs — plus the avoided business disruption that\'s harder to quantify.',
    exampleMetric: 'Preventing 5 exploits per year at $40K recovery cost each = $200K in avoided recovery costs annually.',
    tips: [
      'Ask: "How do you prioritize which vulnerabilities to patch first?"',
      'If the answer is "we patch everything" or "by CVSS score" — that\'s your opening',
      'Threat intelligence-driven prioritization is the differentiator: patching what\'s actually being exploited',
    ],
  },
  {
    id: 'minimise-incident-response-downtime',
    benefitName: 'Minimise Incident Response & Downtime Costs',
    solution: 'security',
    category: 'financial',
    subcategory: 'Risk & Security',
    description: 'Neurons for RBVM reduces the frequency and impact of security incidents by proactively addressing the vulnerabilities most likely to be exploited, minimizing costly incident response and downtime.',
    formula: 'Exploit Response & Downtime Cost per Event × Annual Exploits × % Reduction × Benefit Ramp',
    formulaFactors: ['Response + downtime cost per event (default: $69,800)', 'Annual exploits (default: 5)', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] experiences a security incident that triggers a full incident response — forensics team engaged, systems isolated, 8 hours of downtime at $5,600/hour while the team investigates and contains. The exploited vulnerability had been flagged 6 months earlier but wasn\'t prioritized.',
    talkTrack: 'Every vulnerability that gets exploited triggers an expensive chain: incident response team ($25K), system downtime (8 hours at $5,600/hour = $44.8K), plus data restoration. That\'s nearly $70K per event. RBVM reduces the number of exploitable vulnerabilities by fixing the riskiest ones first — the ones actually being used by attackers. Fewer successful exploits = fewer $70K response events.',
    whyItMatters: 'Incident response is reactive and expensive. Vulnerability management is proactive and comparatively cheap. The math is simple: preventing one $70K incident costs far less than responding to it.',
    exampleMetric: 'Reducing 5 annual exploit events saves approximately $349K per year in incident response and downtime costs.',
    tips: [
      'Walk through the cost breakdown: $25K response + $45K downtime + data restoration',
      'Ask: "How many security incidents required formal incident response last year?"',
      'Connect to the business: "8 hours of downtime at $5,600/hour is $45K before anyone fixes anything"',
    ],
  },
  {
    id: 'reduce-zero-day-defense-cost',
    benefitName: 'Reduce Zero-Day Defense Cost',
    solution: 'security',
    category: 'financial',
    subcategory: 'Patch Management',
    description: 'Neurons for Patch Management enables rapid, automated deployment of critical patches — reducing the cost of responding to zero-day vulnerabilities and minimizing the window of exposure.',
    formula: 'Annual Exploits × Response Cost per Event × % Reduction through Automated Patching × Benefit Ramp',
    formulaFactors: ['Annual smaller scale exploits (default: 5)', 'Response and downtime cost per event (default: $69,800)', 'Reduction through automated patching', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] learns about a critical zero-day vulnerability on a Friday afternoon. Their current patch process — test, approve, schedule, deploy — takes 2-3 weeks. For the next 2 weeks, every system running that software is exposed.',
    talkTrack: 'When a zero-day drops, the clock starts ticking. Your exposure window — the time between "vulnerability announced" and "patch deployed" — is when you\'re most at risk. If your patching process takes 2-3 weeks, that\'s 2-3 weeks of exposure. Automated patching with smart rules closes that window in hours instead of weeks. Test, stage, deploy — automated. The cost savings come from both preventing the exploit and reducing the emergency response effort.',
    whyItMatters: 'Zero-day response is one of the most stressful and expensive activities in IT security. Automation turns it from a fire drill into a process — reducing both the cost and the human toll.',
    exampleMetric: 'Faster zero-day response through automation saves approximately $93.6K per year in reduced defense costs.',
    tips: [
      'Ask: "What\'s your average time from vulnerability announcement to patch deployed?"',
      'Anything over 72 hours for critical vulnerabilities is a strong pain point',
      'The "exposure window" concept is intuitive — everyone understands "the longer you wait, the more risk"',
    ],
  },
  {
    id: 'optimize-remote-access-costs',
    benefitName: 'Optimize Remote Access Costs',
    solution: 'security',
    category: 'financial',
    subcategory: 'Network & Access',
    description: 'Ivanti Connect Secure modernizes remote access with better technology at lower cost — consolidating VPN solutions, reducing hardware requirements, and improving performance.',
    formula: 'Current Remote Access Costs × % Reduction through Modernization × Benefit Ramp',
    formulaFactors: ['Current VPN/remote access infrastructure costs', 'Cost reduction through modernization and consolidation', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] runs multiple legacy VPN solutions acquired through different projects and M&A activity. They\'re paying for overlapping licenses, managing separate infrastructure, and dealing with poor user experience that drives shadow IT.',
    talkTrack: 'Most organizations have accumulated remote access solutions over time — a VPN from 10 years ago, another from an acquisition, a third for a specific use case. Each one has its own licenses, hardware, and management overhead. Connect Secure consolidates that into a modern platform with better security and lower total cost. The savings come from license consolidation, reduced hardware, and simplified management.',
    whyItMatters: 'Legacy VPN sprawl is a cost and security problem. Multiple solutions mean multiple attack surfaces, multiple management consoles, and multiple license costs. Consolidation reduces all three.',
    exampleMetric: 'Consolidating and modernizing remote access infrastructure saves approximately $350K per year.',
    tips: [
      'Ask: "How many different remote access solutions do you have?"',
      'The consolidation story is straightforward: fewer tools = lower cost + better security',
      'User experience matters too — poor VPN drives employees to use unsanctioned alternatives',
    ],
  },
  {
    id: 'elimination-of-password-resets',
    benefitName: 'Elimination of Password Resets',
    solution: 'security',
    category: 'financial',
    subcategory: 'Zero Sign-On',
    description: 'Ivanti Zero Sign-On eliminates passwords entirely — no passwords means no resets, no lockouts, and no stolen credentials. This removes the #1 help desk ticket category.',
    formula: 'Password Reset Tickets × Cost per Reset × Benefit Ramp',
    formulaFactors: ['Password reset ticket volume (% of total tickets)', 'Cost per password reset ticket', 'Benefit Ramp (default: 100%)'],
    scenario: '[Company] help desk processes thousands of password reset tickets per year. Each one takes 8-12 minutes of agent time, and the employee is locked out of work the entire time. It\'s the single largest ticket category.',
    talkTrack: 'Password resets are the #1 help desk ticket at almost every organization — typically 20-30% of total volume. Each one costs you agent time plus the employee\'s idle time. ZSO eliminates them entirely. No passwords means no resets. No lockouts. No "I forgot my password" calls. That\'s not a 10% improvement — it\'s eliminating an entire category of work.',
    whyItMatters: 'Password resets are pure waste — they don\'t add value, they frustrate employees, and they consume help desk capacity that could be used for real issues. Eliminating them is one of the highest-ROI moves in IT.',
    exampleMetric: 'Eliminating password resets saves approximately $561.6K per year in help desk costs and recovered employee productivity.',
    tips: [
      'Ask: "What\'s your #1 help desk ticket category?" — it\'s almost always password resets',
      'Calculate their specific cost: reset tickets × avg handle time × hourly rate',
      'The security angle is equally strong: "no passwords = nothing to steal or phish"',
    ],
  },
];

export function getBenefitById(id: string): BenefitStory | undefined {
  return benefits.find(b => b.id === id);
}

export function getBenefitsBySolution(solution: Solution): BenefitStory[] {
  return benefits.filter(b => b.solution === solution);
}
