// Ivanti Business Capability Toolkit — 36 Capabilities
// Source: Business Capability Cards v2.0 + CoE Toolset Content Master

export type Domain = 'esm' | 'endpoint' | 'exposure' | 'foundations';

export type CapabilityCard = {
  id: string;
  name: string;
  domain: Domain;
  description: string;
  features: string[];
  kpis: string[];
  bestPractices: string[];
  thingsToConsider: string[]; // Yes/No assessment questions
  // Workshop / Study Guide content
  workshopScript: string;
  conversationStarters: string[];
  discoveryQuestions: string[];
};

export const domainConfig: Record<Domain, { label: string; color: string; bgColor: string; borderColor: string }> = {
  esm: { label: 'Enterprise Service Management', color: 'text-blue-400', bgColor: 'bg-blue-500/10', borderColor: 'border-blue-500/20' },
  endpoint: { label: 'Endpoint Management & Security', color: 'text-green-400', bgColor: 'bg-green-500/10', borderColor: 'border-green-500/20' },
  exposure: { label: 'Exposure Management', color: 'text-red-400', bgColor: 'bg-red-500/10', borderColor: 'border-red-500/20' },
  foundations: { label: 'Foundations', color: 'text-purple-400', bgColor: 'bg-purple-500/10', borderColor: 'border-purple-500/20' },
};

export const capabilities: CapabilityCard[] = [
  // ═══════════════════════════════════════════════════════════════
  // ENTERPRISE SERVICE MANAGEMENT (12)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'incident-management',
    name: 'Incident Management',
    domain: 'esm',
    description: 'Maximize employee productivity, restore services, and resolve issues/incidents expediently. Ensure all IT customers can easily contact support to report, track, and fix issues.',
    features: ['Boost employee productivity', 'Restore services', 'Classification and prioritization', 'Single-pane agent view', 'Increase incident deflection', 'Improve agent productivity'],
    kpis: ['Employee productivity', 'Incident deflection', 'Agent productivity', 'Incident experience', 'Incident handle time'],
    bestPractices: [
      'Classify incidents based on severity, impact, and urgency to prioritize response efforts effectively. This helps ensure that critical incidents receive immediate attention.',
      'Give agents and service operations teams full visibility into incidents, cases, and customer data in a single workspace. Agents are no longer left in the dark while being bombarded by frustrated customers.',
    ],
    thingsToConsider: [
      'Are your policies and procedures documented?',
      'Are your incidents truly break/fix items only?',
      'Are tickets routed to the correct teams a majority of the time? (80/20 rule)',
      'Do you measure First Call Resolutions (FCRs)?',
      'Does your organization continuously work to reduce Mean Time to Restore (MTTR)?',
      'Are you tracking cost per ticket?',
    ],
    workshopScript: 'Let\'s talk about how your organization handles incidents today. When something breaks — a system goes down, an application crashes, a user can\'t access what they need — what happens? I want to understand the full journey: how does the user report it, how does it get to the right person, and how fast does it get resolved?',
    conversationStarters: [
      'Walk me through what happens when a critical system goes down at 2pm on a Tuesday.',
      'If I\'m an employee and my laptop stops working, what\'s my first step? Who do I call?',
      'How would you rate your team\'s ability to get the right ticket to the right person, first time?',
    ],
    discoveryQuestions: [
      'How many tickets does your service desk handle per month, and how does that break down between incidents vs. service requests?',
      'What\'s your current first call resolution rate — and are you happy with it?',
      'Do your agents have a single view of the user, their devices, and their ticket history when they pick up a call?',
      'How do you currently measure and track cost per ticket?',
      'What percentage of tickets get routed to the wrong team on the first pass?',
    ],
  },
  {
    id: 'problem-management',
    name: 'Problem Management',
    domain: 'esm',
    description: 'Identify, diagnose, and resolve the root causes of recurring incidents to improve overall service quality and minimize disruptions. Unlike incident management, which addresses immediate issues, problem management aims to identify underlying issues and implement appropriate solutions to prevent future incidents.',
    features: ['Eliminate recurring incidents', 'Accelerate service restoration', 'Create remediation plans', 'Automate notifications', 'Gain insights from real-time analytics'],
    kpis: ['Service restoration', 'Root cause analysis', 'Insights and analytics', 'Service disruptions', 'Recurring incidents'],
    bestPractices: [
      'Separate incidents from problems and keep a known error knowledge database.',
      'Identify a dedicated problem manager to investigate and document not just the what, but also the why.',
      'Ensure agents and operators contribute constantly to improve a shared knowledge base.',
    ],
    thingsToConsider: [
      'Have you defined your policies and procedures for what constitutes a problem?',
      'Are you tracking root cause, impact, symptoms, and service restoration time of a problem?',
      'Do you have a postmortem process to identify recurring problems?',
      'Are problem tickets linked back to completed change requests that may have caused the widespread issue?',
      'Do you provide workarounds within your problem tickets?',
      'Do you maintain a knowledge base with problem records and solutions?',
    ],
    workshopScript: 'Now let\'s shift from fighting fires to preventing them. Problem management is about asking "why does this keep happening?" instead of just fixing it again. I want to explore whether your team has the time and process to look deeper than the symptoms.',
    conversationStarters: [
      'Think about your top 5 most frequent incidents last quarter. How many of those are the same issue repeating?',
      'When a major incident happens, do you do a formal postmortem — and does anyone actually read it?',
      'Do you have someone whose specific job is to investigate root causes, or does everyone just move to the next ticket?',
    ],
    discoveryQuestions: [
      'What percentage of your monthly incidents are repeat issues with a known root cause?',
      'Do you have a formal process that distinguishes between incidents (symptoms) and problems (root causes)?',
      'When was the last time a root cause analysis actually prevented a future incident?',
      'Are your problem records linked to the change requests that might have caused them?',
      'Do you maintain a known error database that agents can reference during incident resolution?',
    ],
  },
  {
    id: 'change-management',
    name: 'Change Management',
    domain: 'esm',
    description: 'Accelerate, simplify, and automate complex change processes, with full risk and impact info. Minimize impact of change on service quality and reduce operational costs.',
    features: ['Integrate organization-wide change processes', 'Reduce service impact', 'Change approval policies', 'Change management lifecycle', 'Enhance proficiency and accuracy'],
    kpis: ['Change velocity', 'Employee productivity', 'Agent productivity', 'Technical debt', 'Risk intelligence', 'Failure rate'],
    bestPractices: [
      'Automate change requests for dependencies, conflicts, and approval workflows.',
      'Increase change velocity by measuring change requests/orders on an organization-wide basis to improve operational efficiency.',
      'Make change requests automatically screened for dependencies and conflicts, and add the change order approver.',
      'Maximize automation of approvals to shorten the change management lifecycle and improve accuracy and efficiency.',
    ],
    thingsToConsider: [
      'Have you defined your policies and procedures for change requests?',
      'Are you tracking the success rate % of change requests?',
      'Are approvals automatically routed to the correct system owners related to the change?',
      'Are you measuring your change velocity and thinking of ways to increase the delivery speed of change requests?',
      'Are you aware of the dependencies between CIs, critical IT systems, services, and infrastructure components?',
    ],
    workshopScript: 'Changes are inevitable — new features, patches, infrastructure updates. The question is whether your change process enables speed or creates bottlenecks. Let\'s explore how changes move through your organization and where things get stuck or go wrong.',
    conversationStarters: [
      'When was the last time a change caused an unexpected outage? What happened?',
      'If you need to push an emergency change on a Friday afternoon, what does that process look like?',
      'How long does a standard change take from request to implementation?',
    ],
    discoveryQuestions: [
      'What percentage of your outages are caused by changes that had unintended downstream effects?',
      'How do you currently assess the impact of a proposed change — do you have dependency visibility?',
      'What\'s your change success rate, and are you tracking it formally?',
      'How many changes per month require emergency approval, and what triggers that?',
      'Are your change approvals automated or manual email chains?',
    ],
  },
  {
    id: 'knowledge-management',
    name: 'Knowledge Management',
    domain: 'esm',
    description: 'Manage knowledge articles and FAQs to drive self-service for incident resolution. Boost agent productivity with AI-powered contextual knowledge.',
    features: ['Article workflow and taxonomy', 'Crowd sourced knowledge', 'Article approval workflow', 'Streamline continuous improvements', 'Analytics and dashboards'],
    kpis: ['Incident/request deflection', 'Self-service rates', 'Agent productivity', 'Incident handle time', 'CSAT scores', 'Case/incident volume'],
    bestPractices: [
      'Design your knowledge base with a user-centric approach.',
      'Make it easy to find information and navigate content, using features like content collaboration, version control, and search.',
      'Track usage metrics to understand how users interact with your knowledge base.',
      'Encourage user feedback on knowledge base content to identify gaps and improve user experience.',
    ],
    thingsToConsider: [
      'Have you established a knowledge base where information, documents, and best practices are stored and easily accessible?',
      'Are your knowledge articles categorized for easy search and retrieval?',
      'Have you implemented processes for content and quality control to ensure information is accurate, up-to-date, and relevant?',
      'Do you regularly review and update processes to ensure continuous improvement?',
      'Do you track key metrics and analytics related to usage, engagement, and effectiveness?',
    ],
    workshopScript: 'Knowledge management is the foundation of everything — self-service, agent productivity, incident deflection. If your knowledge base is outdated or hard to find, everything downstream suffers. Let\'s talk about how knowledge flows in your organization.',
    conversationStarters: [
      'If I searched your knowledge base right now for "VPN not connecting," would I find a useful, current article?',
      'Who owns your knowledge base — is there a dedicated team, or is it everyone\'s job and nobody\'s job?',
      'When an agent resolves a tricky issue, does that solution get captured somewhere — or does it live in their head?',
    ],
    discoveryQuestions: [
      'How many knowledge articles do you have, and when was the last time they were reviewed for accuracy?',
      'What percentage of your tickets could have been resolved by a knowledge article if the user could find it?',
      'Do your agents get contextual knowledge suggestions when working on a ticket?',
      'How do you currently measure the effectiveness of your knowledge base?',
      'Is there a formal process for creating articles from resolved incidents?',
    ],
  },
  {
    id: 'self-service',
    name: 'Self-Service (Request Management)',
    domain: 'esm',
    description: 'Provide self-service for employees and customers. Make it easy to request products, services, and answers anytime, on any device.',
    features: ['Boost user satisfaction and experience', 'Meet users where they are', 'Service catalog workspace', 'Simplify approval workflows', 'Improve productivity across the enterprise', 'Improve self-service through automation'],
    kpis: ['Service and task efficiencies', 'Agent productivity', 'Quick and easy approvals', 'User experience', 'Visibility and analysis', 'Case resolution time'],
    bestPractices: [
      'Measure case deflection in order to continuously improve efficacy and reduce costs, including: explicit, repetitive, and implicit deflection.',
      'Optimize ease of use, with single sign-on mobile support, and embedded self-services.',
      'Leverage self-service to progressively grow a user\'s profile.',
    ],
    thingsToConsider: [
      'Do your field users have the ability to find service offerings in a user-friendly portal?',
      'Is your service catalog categorized and easy to navigate?',
      'Are you tracking service request usage and retiring offerings that are not used?',
      'Are you designing offerings to capture all required information, removing the need to reach out to the requester?',
      'Do you offer guidance to assist users through filling out a request?',
    ],
    workshopScript: 'Self-service is where IT meets the employee experience. If your portal is hard to use, people bypass it and call the help desk. Let\'s explore what self-service looks like in your organization and where the friction points are.',
    conversationStarters: [
      'If a new employee needs to request software access on their first day, how easy is that process?',
      'What percentage of your employees actually use the self-service portal vs. calling or emailing IT?',
      'When was the last time you retired a service catalog offering that nobody was using?',
    ],
    discoveryQuestions: [
      'What\'s your current self-service adoption rate across the organization?',
      'Are your service catalog items designed to capture everything needed upfront, or do agents have to follow up for more info?',
      'How do approval workflows work today — are they automated or manual?',
      'Do you have visibility into which catalog items are most and least used?',
      'Can employees access self-service on mobile devices?',
    ],
  },
  {
    id: 'analyst-workspace',
    name: 'Analyst Workspace',
    domain: 'esm',
    description: 'A comprehensive, customizable environment that enables analysts to efficiently view, organize, and analyze data to generate insights and actionable recommendations. Enable quick identification and resolution of service issues.',
    features: ['Improve analyst efficiency', 'Integrate communication channels', 'Accelerate issue and request resolution', 'Enable layout customization', 'Link user and device information'],
    kpis: ['First call resolution', 'CSAT scores', 'Field agent satisfaction', 'Time to first response', 'MTTR'],
    bestPractices: [
      'Leverage skill-based routing, screen pops to identify caller profiles, and quick action activities that encapsulate many steps in a single action.',
      'Save and retrieve recent activities and transfer ticket content to other teams or agents.',
      'Enable analysts to multitask and become more efficient.',
    ],
    thingsToConsider: [
      'Do your analysts have a dashboard that provides all of the information they need to fulfill their day-to-day tasks?',
      'Are you designing dashboards for specific teams and roles, containing information and KPIs that would be most important to their jobs?',
      'Is your organization leveraging operational dashboards to manage workloads efficiently against service quality?',
      'Do your team managers have a dashboard that shows CSAT and workloads for their employees?',
      'Are you empowering your analysts with real-time data that could help identify trends?',
    ],
    workshopScript: 'Your analysts are the front line. If their workspace is cluttered, slow, or forces them to jump between tools, every ticket takes longer. Let\'s look at what your analyst experience looks like today.',
    conversationStarters: [
      'How many different tools or tabs does an analyst have open to resolve a single ticket?',
      'Can your analysts see the user\'s device info, ticket history, and asset details without leaving their workspace?',
      'Do your team leads have real-time visibility into queue depth and individual agent workload?',
    ],
    discoveryQuestions: [
      'Do your analysts have role-specific dashboards, or does everyone see the same generic view?',
      'How much time per ticket is spent context-switching between tools?',
      'Can analysts take quick actions (like password reset or software push) directly from the ticket view?',
      'Are your managers able to see real-time CSAT and workload data for their team?',
      'Do your analysts get screen pops with caller context when a call comes in?',
    ],
  },
  {
    id: 'automation-predictive-intelligence',
    name: 'Automation & Predictive Intelligence',
    domain: 'esm',
    description: 'Coordinate the use of multiple technologies, tools, and platforms, including machine learning (ML) and predictive intelligence, to automate business and IT processes.',
    features: ['Improve service quality', 'Enhance decision making', 'Improve workflow design', 'Innovation enablement', 'Boost employee and agent productivity', 'Strategic resource allocation'],
    kpis: ['CSAT scores', 'Incident deflection', 'Response time', 'Resolution times', 'Support costs'],
    bestPractices: [
      'Incorporate hyperautomation and predictive intelligence in service management to streamline operations and proactively address issues.',
      'Automate routine tasks and predict potential challenges to increase efficiency and reduce downtime.',
      'Empower service teams to leverage predictive insights to make informed decisions, optimize resource allocation, and enhance overall service quality.',
    ],
    thingsToConsider: [
      'Does your organization leverage automation tools to streamline repetitive tasks and processes?',
      'Does your organization utilize predictive analytics to anticipate and address potential issues before they occur?',
      'Is your organization\'s integration of automation and predictive intelligence across incident, change, and asset management mature?',
      'Does your organization measure the impact and effectiveness of automation and predictive intelligence initiatives?',
      'Is your automation and predictive intelligence improving CSAT score across your enterprise?',
    ],
    workshopScript: 'Automation is where you get the biggest multiplier on everything else. If your team is manually doing things that could be automated, you\'re leaving efficiency on the table. Let\'s explore where automation could have the biggest impact for you.',
    conversationStarters: [
      'What are the top 3 most repetitive tasks your IT team does every day that could theoretically be automated?',
      'Have you experimented with any AI or ML capabilities in your service management environment?',
      'If you could wave a magic wand and automate one process tomorrow, what would it be?',
    ],
    discoveryQuestions: [
      'What percentage of your workflows involve manual steps that could be automated?',
      'Are you using any predictive analytics to anticipate issues before users report them?',
      'How do you measure the ROI of automation initiatives today?',
      'Is your automation strategy integrated across incident, change, and asset management, or siloed?',
      'What\'s the biggest barrier to adopting more automation — technology, process, or culture?',
    ],
  },
  {
    id: 'ci-inventory',
    name: 'Configuration Item (CI) Inventory',
    domain: 'esm',
    description: 'A digital enterprise management capability helps you to discover and manage all CIs. Inventory all network devices across multiple operating systems and industry protocols.',
    features: ['Build a single source of truth', 'Ingest 3rd party data', 'Improve visibility across multi-cloud environments', 'Interrogate data to create operational efficiencies'],
    kpis: ['Actionable insights', 'Security compliance', 'Scalability', 'Resource bandwidth', 'Time to value', 'Unknown endpoints'],
    bestPractices: [
      'Discover your entire IT infrastructure, creating an accurate and up-to-date record in your CMDB.',
      'Discover both physical and logical components, including virtual machines, servers, storage, databases, applications, and more.',
      'Leverage the data to identify environment inconsistencies, optimize processes, and reduce risk.',
    ],
    thingsToConsider: [
      'Have you defined the components you want to keep in CI inventory?',
      'Is your CI inventory updated on a regular cadence?',
      'Do you have a process to prevent duplicate records and/or data being overwritten?',
      'Are you getting value from your CI records?',
      'Is your CI solution scalable?',
      'Do you have a defined process around adding new CIs and updating existing CI content/status?',
    ],
    workshopScript: 'Your CI inventory is the foundation of your CMDB and, by extension, everything that depends on accurate data — change management, incident resolution, security posture. If it\'s stale or incomplete, decisions made on top of it are flawed. Let\'s see where you are.',
    conversationStarters: [
      'If I asked you right now how many servers are running in your environment, how confident are you in that number?',
      'When was the last time your CI data surprised you — something was there that shouldn\'t have been, or vice versa?',
      'Do you trust the data in your CMDB enough to make change decisions based on it?',
    ],
    discoveryQuestions: [
      'How often is your CI inventory refreshed — daily, weekly, monthly, or only when someone remembers?',
      'Do you have a process to prevent duplicate or stale CI records?',
      'Are you ingesting CI data from third-party sources, or is it all manually maintained?',
      'Can your CI inventory scale to cover cloud, virtual, and containerized environments?',
      'What percentage of your CIs would you say are accurately documented right now?',
    ],
  },
  {
    id: 'field-worker-agent-mobility',
    name: 'Field Worker & Agent Mobility',
    domain: 'esm',
    description: 'Enhance the ability of agents and field workers to complete key work functions from anywhere. Give agents a mobile interface to triage, address, and resolve requests on the go.',
    features: ['Manage team performance', 'Simplify work', 'Maximize efficiency', 'Increase productivity'],
    kpis: ['Field employee productivity', 'Field service management', 'Field team performance', 'Incident handle time'],
    bestPractices: [
      'Leverage mobile hardware/software including touchscreens for eSignature, barcode scanning, notifications for real-time work changes, and access to service requests, incidents, and tasks to support work regardless of network connectivity.',
      'Empower field personnel to work from any location without losing the ability to perform basic work functions.',
    ],
    thingsToConsider: [
      'Do your users have the ability to complete required work from anywhere?',
      'Do your users have the equipment necessary to complete tasks and answer calls remotely?',
      'Do you measure the effectiveness and efficiency of your remote workers vs. office-based agents?',
      'Do your users have real-time communication and collaboration tools?',
      'Do you effectively allocate field workers based on priority, location, and availability?',
    ],
    workshopScript: 'In today\'s hybrid world, your agents and field workers need to be productive whether they\'re in the office, at home, or on-site. Let\'s explore how mobile your workforce really is and where they hit walls.',
    conversationStarters: [
      'Can your field technicians access and update tickets from a mobile device while on-site?',
      'What happens when a field worker is at a location with no connectivity — can they still work?',
      'How do you allocate field work — is it manual dispatch or intelligent routing based on location and skills?',
    ],
    discoveryQuestions: [
      'What percentage of your workforce operates primarily outside of a traditional office setting?',
      'Can your agents resolve tickets from a mobile device, or do they need to be at a desktop?',
      'Do you have offline capability for field workers in low-connectivity environments?',
      'How do you measure field worker productivity compared to office-based staff?',
      'Are field workers assigned work based on proximity, skill, and availability — or is it manual?',
    ],
  },
  {
    id: 'service-level-management',
    name: 'Service Level Management',
    domain: 'esm',
    description: 'Ensure all service management activities and service delivery processes are aligned with service level agreements to deliver reliable and predictable business outcomes.',
    features: ['Strengthen the service provider business relationship', 'Enhance organizational performance', 'Centralize SLA management', 'Improve visibility of service timeline'],
    kpis: ['Workload visibility', 'CSAT scores', 'Service delivery', 'Proactive service issues', 'Number of SLA breaches'],
    bestPractices: [
      'Set up SLAs with customers to define commitments to entitlements, milestones, and asset delivery.',
      'Increase productivity by managing cases that agents use to interact with customers to resolve service issues and ensure expected outcomes.',
    ],
    thingsToConsider: [
      'Do you have SLAs defined?',
      'Are you tracking delivery/handle time for your service requests?',
      'Do your teams gather customer feedback through surveys?',
      'Are you tracking MTTR for common incident types?',
      'Are SLAs visible to the request/incident submitter, and are they accurate?',
    ],
    workshopScript: 'SLAs are the contract between IT and the business. If you\'re not measuring against them — or worse, if they\'re not defined — there\'s no shared understanding of what "good" looks like. Let\'s assess where you stand.',
    conversationStarters: [
      'Do your end users know what SLA applies to their ticket? Can they see where it is in the timeline?',
      'When was the last time you reviewed and updated your SLAs — are they still relevant?',
      'How do you handle an SLA breach today? Is there an escalation path or does it just get flagged?',
    ],
    discoveryQuestions: [
      'How many SLA tiers do you have, and are they aligned with business priority?',
      'What\'s your current SLA breach rate — and is it trending up or down?',
      'Do you gather CSAT data after ticket resolution?',
      'Are SLAs consistent across departments, or does each team have its own definitions?',
      'Can you report on SLA performance in real-time, or only after the fact?',
    ],
  },
  {
    id: 'service-quality-analytics',
    name: 'Service Quality & Analytics',
    domain: 'esm',
    description: 'Service quality is crucial for customer satisfaction and retention. By leveraging advanced analytics, businesses can gain deep insights into service performance and enhance the overall customer experience.',
    features: ['Improve resource utilization', 'Interrogate data to create service and operational efficiencies', 'Customizable on-demand analytics', 'Enhance decision-making through improved visibility'],
    kpis: ['Agility and visibility', 'Employee experience', 'Employee satisfaction', 'Average handling time'],
    bestPractices: [
      'Analyze the agent and customer experience, including sentiment, to develop comprehensive training and resolve customer issues efficiently.',
      'Integrate customer feedback into your analytics processes to continuously identify and address areas for improvement.',
    ],
    thingsToConsider: [
      'Do you leverage data from service quality analytics to make decisions and drive improvements?',
      'Do you collect, analyze, and report on service quality metrics?',
      'Do you have standardized processes for monitoring, measuring, and improving service quality?',
      'Are you fostering a culture of continuous improvement regarding service quality?',
    ],
    workshopScript: 'You can\'t improve what you don\'t measure. Service quality analytics tells you not just what happened, but why — and what to do about it. Let\'s explore how data-driven your service management decisions really are.',
    conversationStarters: [
      'When leadership asks "how is IT performing?" — what data do you show them?',
      'Do you analyze sentiment or just resolution metrics? Do you know if users are satisfied or just quiet?',
      'How quickly can you pull a report on service quality across teams?',
    ],
    discoveryQuestions: [
      'What service quality metrics do you currently track, and how often are they reviewed?',
      'Do you have on-demand analytics, or are reports manually compiled?',
      'How do you use analytics to make resource allocation decisions?',
      'Are you measuring the agent experience alongside the customer experience?',
      'Can you identify trends — like a specific app causing a spike in tickets — from your analytics?',
    ],
  },
  {
    id: 'enterprise-onboarding',
    name: 'Enterprise Onboarding, Transitions & Offboarding',
    domain: 'esm',
    description: 'A streamlined, agile process for integrating new employees or transitioning existing employees efficiently. This process is essential for maintaining high service standards and achieving employee satisfaction.',
    features: ['End-to-end visibility', 'Step-by-step guidance', 'Simplify onboarding through automation', 'Centralized employee lifecycle', 'Customizable workflow design'],
    kpis: ['Employee experience', 'Enterprise productivity and efficiency', 'Employee 1st day experience', 'Employee retention', 'CSAT scores', 'Time to value'],
    bestPractices: [
      'Ensure that the onboarding process is scalable and flexible.',
      'Use logical workflows to create a personalized experience that is accessible on any device.',
      'Enable coordination between all departments that are part of the onboarding, transition, and offboarding processes.',
    ],
    thingsToConsider: [
      'Do you sequence onboarding and transition tasks efficiently to grant access to applications and devices?',
      'Are your tasks automatically assigned to the correct teams in all situations?',
      'Do you reduce human error during the onboarding process to limit HR corrections?',
      'Can you efficiently set up a new hire to be ready to work in a reasonable timeframe?',
      'Do you have a process for removing application privileges when employees move to a new role?',
      'Is your data accurate and are you leveraging a single source of truth?',
    ],
    workshopScript: 'The employee lifecycle — onboarding, role transitions, offboarding — touches every department. When it\'s manual, things fall through the cracks. New hires wait days for access, departing employees keep access for weeks. Let\'s map your current process.',
    conversationStarters: [
      'How many days does it take from a new hire\'s start date to them being fully productive with all the tools they need?',
      'When someone leaves the organization, how quickly is all their access revoked?',
      'If an employee changes roles internally, what happens to their previous access and permissions?',
    ],
    discoveryQuestions: [
      'How many departments are involved in your onboarding process, and how is coordination handled?',
      'What\'s the average time to fully provision a new hire?',
      'When an employee departs, how long before their access is completely revoked?',
      'Do you have automated workflows for role transitions, or is it manual access review?',
      'How do you ensure data accuracy across HR, IT, and facilities during the lifecycle?',
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // ENDPOINT MANAGEMENT & SECURITY (12)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'unified-endpoint-management',
    name: 'Unified Endpoint Management (UEM)',
    domain: 'endpoint',
    description: 'See, manage, configure, and secure every device from one simple interface. Enforce policies and privileges everywhere in a few clicks. Discover and patch threats predictively and quickly.',
    features: ['Distribution and provisioning', 'Application management', 'Analytics and reporting', 'Device lifecycle management'],
    kpis: ['Device compliance', 'ISO compliance', 'Employee/Agent productivity', 'Streamlined operations', 'CSAT scores', 'Operational costs', 'Cybersecurity gaps'],
    bestPractices: [
      'Find and track all devices that connect to your IT estate and keep them safe by installing and maintaining the latest operating systems, security software, and patches.',
      'Augment with Zero Trust security principles on user privileges. Educate users about vulnerabilities such as unregulated USB port access.',
      'Discover and fix vulnerabilities rapidly while maintaining an audit trail.',
    ],
    thingsToConsider: [
      'Does your organization have a UEM solution in place?',
      'Does your UEM solution help ensure compliance with internal security policies?',
      'Does your UEM solution allow management of multiple operating systems?',
      'Are you able to manage all areas of UEM (SWD, patch, OS provisioning, reporting, etc.)?',
      'Do you have the appropriate administration (role-based access) configured?',
      'Are you leveraging the vendor/partner landscape to drive adoption and value?',
    ],
    workshopScript: 'Endpoint management is about having one place to see, manage, and secure every device in your environment — laptops, desktops, servers, mobile. Let\'s understand how unified your approach really is, or if you\'re juggling multiple tools.',
    conversationStarters: [
      'How many different tools do you use to manage endpoints across your environment?',
      'Can you manage Windows, Mac, Linux, iOS, and Android from a single console?',
      'If a critical vulnerability is announced today, how quickly can you identify and patch every affected device?',
    ],
    discoveryQuestions: [
      'Do you have a single solution managing all endpoint types, or separate tools for desktop vs. mobile?',
      'How do you handle OS provisioning for new devices — is it automated or manual?',
      'What\'s your current device compliance rate across the fleet?',
      'Can you report on the patch status and security posture of every endpoint right now?',
      'How do you manage the full device lifecycle — from procurement through retirement?',
    ],
  },
  {
    id: 'endpoint-security',
    name: 'Endpoint Security',
    domain: 'endpoint',
    description: 'Comprehensively enforce security policies that establish a baseline of normal activity. Continuously monitor and analyze systems to prevent malicious actors from exploiting legitimate tools and resources.',
    features: ['Detect device and user behaviors', 'Allow device and action control', 'Risk mitigation', 'Improve compliance management'],
    kpis: ['Employee productivity', 'Device compliance', 'Data visibility', 'IT costs', 'Organizational risk'],
    bestPractices: [
      'Implement strong access controls such as multi-factor authentication (MFA) and role-based permissions.',
      'Continuously monitor activity and conduct regular security audits to detect and respond to anomalies.',
      'Provide ongoing security training and awareness programs.',
    ],
    thingsToConsider: [
      'Do you have visibility into your security posture for each device, regardless of type and OS?',
      'Are you managing the security risks associated with third-party vendors?',
      'Can you see and manage all corporate devices regardless of location?',
      'Are you leveraging technologies for threat detection and prevention on endpoints?',
      'Are you effectively managing patches and performing vulnerability assessment on endpoints?',
    ],
    workshopScript: 'Endpoint security is your last line of defense. Every device is a potential entry point. Let\'s assess how well you can see, manage, and protect every device in your environment — including the ones you might not know about.',
    conversationStarters: [
      'Do you have visibility into the security posture of every device — desktop, mobile, server — regardless of OS?',
      'What happens when a device starts exhibiting unusual behavior — do you detect that automatically?',
      'How do you manage third-party vendor access to your endpoints?',
    ],
    discoveryQuestions: [
      'Can you see the security status of every device regardless of type and location?',
      'Are you using EDR or behavioral analytics to detect anomalous endpoint activity?',
      'How do you enforce security policies across BYOD and contractor devices?',
      'What\'s your process for handling a compromised endpoint?',
      'How do you ensure all endpoints are patched and compliant?',
    ],
  },
  {
    id: 'ztna',
    name: 'Zero Trust Network Access (ZTNA)',
    domain: 'endpoint',
    description: 'Provide users access to specific applications based on user location, device, or access privileges. Continuously assess for risks and allow admins to create policies to define access decisions.',
    features: ['Security framework compliance', 'Centralize administration', 'Public and customer-facing conditional access', 'Support hybrid or remote working', 'Continual risk assessment'],
    kpis: ['Visibility and analytics', 'User productivity', 'Securing enterprise environments', 'Service disruptions', 'Insider threat risks'],
    bestPractices: [
      'Ensure device security compliance before granting access to specified applications through granular segmentation.',
      'Continually monitor sessions for risks, enabling administrators to create policies informed by real-time risk analysis.',
    ],
    thingsToConsider: [
      'Do you manage and authenticate identities in a Zero Trust model?',
      'Have you modernized your network architecture to provide secure access regardless of location?',
      'Is your Zero Trust architecture integrated with your existing security tools?',
      'Do you ensure user security parameters before connecting to network resources?',
      'Do you leverage UEBA to detect and respond to unusual behavior?',
    ],
    workshopScript: 'Zero Trust means "never trust, always verify." It\'s a fundamental shift from perimeter-based security to identity-and-context-based access. Let\'s explore how far along your organization is on this journey.',
    conversationStarters: [
      'Does your current model trust devices once they\'re on the network, or do you verify continuously?',
      'How do you handle access for remote workers — VPN, or something more modern?',
      'If a user\'s device becomes compromised during a session, is access revoked immediately or at next login?',
    ],
    discoveryQuestions: [
      'Are you operating on a Zero Trust model, or still primarily perimeter-based security?',
      'How do you handle conditional access based on device posture, location, and user identity?',
      'Is your ZTNA integrated with your existing security and identity tools?',
      'Do you perform continuous risk assessment during active sessions?',
      'How do you manage access for contractors and third parties?',
    ],
  },
  {
    id: 'physical-asset-inventory',
    name: 'Physical Asset Inventory',
    domain: 'endpoint',
    description: 'The systematic process to track and control physical assets throughout their lifecycle, from acquisition to disposal. Involves identification, documentation, and monitoring of assets.',
    features: ['Inventory and regional distribution centers', 'Financial asset management', 'Operational efficiency and equipment status', 'Loss prevention, governance and compliance'],
    kpis: ['Asset availability', 'New hire onboarding experience', 'User experience and productivity', 'Emergency purchases', 'Costs and overtime expenses', 'Business user downtime'],
    bestPractices: [
      'Effective physical asset management involves regular maintenance, thorough documentation, and strategic planning.',
      'Utilize technology such as asset management software, barcode scanners, and RFID tags to streamline tracking.',
      'Foster a culture of accountability and continuous improvement.',
    ],
    thingsToConsider: [
      'Are you enabling savings and delivering a positive user experience by reducing expedited shipping?',
      'Is your field inventory accurate?',
      'Do you leverage a framework to forecast inventory needs and plan for replenishments?',
      'Do you integrate a replenishment threshold with your suppliers?',
      'Do you have a scanning tool to update inventory in a timely manner?',
    ],
    workshopScript: 'Physical assets — laptops, monitors, keyboards, mobile devices — are a significant investment. Let\'s look at how you track them from the moment they\'re purchased to when they\'re retired.',
    conversationStarters: [
      'When a new hire starts, is there a device ready and waiting for them — or does someone scramble to find one?',
      'Do you know, right now, how many spare devices are in your distribution centers?',
      'How many emergency hardware purchases happened last quarter because planned inventory ran out?',
    ],
    discoveryQuestions: [
      'How do you track physical hardware inventory — automated scanning, spreadsheets, or something else?',
      'What\'s your emergency purchase rate? How often do you have to expedite hardware orders?',
      'Do you have regional distribution centers, and is inventory balanced across them?',
      'How accurate is your current inventory — within 5%, 10%, or no idea?',
      'Do you have replenishment thresholds that trigger automated orders?',
    ],
  },
  {
    id: 'itam',
    name: 'IT Asset Management (ITAM)',
    domain: 'endpoint',
    description: 'Use core IT asset management to support financial, contractual, and risk management activities. Manage the lifecycle of IT assets, from request to disposal.',
    features: ['End-to-end asset lifecycle and vendor management', 'Total cost of ownership', 'Discovery and inventory', 'Audit and compliance', 'Mitigate IT asset risk', 'Track purchase details and warranty status'],
    kpis: ['Asset visibility', 'End user experience', 'Asset cost visibility', 'Operational efficiencies', 'Non-budgeted replacement expenses', 'Support costs', 'Security risk'],
    bestPractices: [
      'Regularly update and maintain a centralized asset repository to ensure accurate tracking throughout the lifecycle.',
      'Conduct periodic audits and assessments to identify discrepancies, optimize utilization, and support informed decisions.',
    ],
    thingsToConsider: [
      'Are you assigning the cost of the asset to an owner/department?',
      'Do you know how many assets your organization owns and where they are?',
      'Are you managing your assets through the various stages of the lifecycle from procurement to disposal?',
      'If a device is lost or stolen, can you identify asset assignment and wipe it remotely?',
      'Do you use a dynamic asset management database?',
    ],
    workshopScript: 'ITAM connects the dots between what you own, what it costs, and whether it\'s being used. It\'s the bridge between procurement, finance, IT, and security. Let\'s see how well those connections work in your environment.',
    conversationStarters: [
      'If I asked you right now how many total assets your organization owns and their total cost, how fast could you answer?',
      'When a device is reported lost or stolen, what\'s the process — and how long does it take to remotely wipe it?',
      'Are you tracking total cost of ownership per asset, or just the purchase price?',
    ],
    discoveryQuestions: [
      'Do you have a centralized asset database, or is asset data spread across multiple systems?',
      'Can you track an asset from procurement through deployment, maintenance, and retirement?',
      'How do you handle warranty and maintenance contract tracking?',
      'Are asset costs assigned to departments or cost centers?',
      'What happens when a device reaches end-of-life — is there a defined process?',
    ],
  },
  {
    id: 'software-procurement',
    name: 'Software Procurement',
    domain: 'endpoint',
    description: 'The process of identifying, acquiring, and managing software licenses. This involves evaluating needs, researching solutions, negotiating contracts, and ensuring compliance with licensing agreements.',
    features: ['Financial management of software', 'Maintain high operational efficiency', 'Accurate ongoing inventory of software', 'Governance and compliance', 'Automate replenishment of licenses'],
    kpis: ['Software availability', 'New hire onboarding experience', 'User experience and productivity', 'Emergency purchases', 'Costs and audit expenses', 'Business user downtime'],
    bestPractices: [
      'Establish a comprehensive inventory management system to track all software assets, including licenses, usage, and expiration dates.',
      'Regularly review and update this inventory to ensure accurate count and compliance.',
      'Implement a software lifecycle management plan, from acquisition through deployment, usage, and eventual retirement.',
    ],
    thingsToConsider: [
      'Do you know what your software entitlement license portfolio entails?',
      'Have you established a centralized software procurement team or process?',
      'Do you effectively inventory, transition, and audit software licenses?',
      'Have you established your software asset management lifecycle, from procurement to retirement?',
      'Do you have a threshold for automatic software procurement on high volume software assets?',
    ],
    workshopScript: 'Software is often one of the largest IT budget line items, but it\'s also one of the least well-managed. Shelfware, over-licensing, surprise audit costs — let\'s explore how well you manage the software lifecycle.',
    conversationStarters: [
      'Do you know, right now, how many unused software licenses your organization is paying for?',
      'When was the last time you were surprised by a software audit, and what did it cost?',
      'Is there an automated process to reclaim licenses when employees leave, or does that slip through?',
    ],
    discoveryQuestions: [
      'Do you have a complete inventory of all software licenses, including usage data?',
      'Is there a centralized team or process for software procurement?',
      'How do you handle license compliance and prepare for vendor audits?',
      'Do you have automatic replenishment triggers for high-volume license pools?',
      'What\'s your estimated shelfware rate — licenses paid for but not actively used?',
    ],
  },
  {
    id: 'dex',
    name: 'Digital User Experience Management (DEX)',
    domain: 'endpoint',
    description: 'Track, measure, and optimize your employees\' digital experience to improve productivity, security, and retention. Enhance the digital experience across devices and applications.',
    features: ['Improve end user efficiency', 'Integrate communication channels', 'Omnichannel self-service assistance', 'Proactive diagnostics and remediation'],
    kpis: ['Employee productivity', 'Employee CSAT', 'Resource bandwidth', 'Resourcing costs', 'Incident count', 'Undetected service impacts'],
    bestPractices: [
      'Aggregate and monitor usage, performance, and security data from all devices and applications employees rely on.',
      'Go beyond post-ticket surveys and collect contextual sentiment to gauge employees\' digital experience.',
      'Drive continuous improvement and predict productivity degradation.',
      'Surface potential IT and security issues and make recommendations on remediation.',
    ],
    thingsToConsider: [
      'Do you have an enablement program around digital user experience management?',
      'Are experiences on digital devices replicated across all platforms?',
      'Does your digital experience offer seamless sign-on and secure authentication?',
      'Do you monitor and resolve potential problems before they impact end users?',
      'Do you offer digital self-service?',
      'Are you able to health score your digital devices under management?',
    ],
    workshopScript: 'Digital employee experience is the new battleground for productivity and retention. If your employees\' devices are slow, apps crash, or login is painful — they\'re losing time and patience every day. Let\'s assess the digital experience in your organization.',
    conversationStarters: [
      'How do you know if your employees are having a good or bad digital experience right now?',
      'Can you proactively detect that a user\'s device is degrading before they submit a ticket?',
      'Do you measure digital experience beyond CSAT surveys — actual device performance, app load times?',
    ],
    discoveryQuestions: [
      'Do you have a DEX program, or is digital experience measured only through tickets and surveys?',
      'Can you health-score every device under management in real time?',
      'Are you proactively remediating issues before users notice them?',
      'Is the digital experience consistent across platforms — Windows, Mac, mobile?',
      'How do you measure the productivity impact of digital experience issues?',
    ],
  },
  {
    id: 'proactive-remote-support',
    name: 'Proactive & Remote Support',
    domain: 'endpoint',
    description: 'Anticipate potential issues and resolve them before they impact users. Provide support using remote access and monitoring tools. Resolve issues quickly across a hybrid workforce.',
    features: ['Audit log of remote sessions', 'Option to record remote control sessions', 'Compliance with security policies', 'Proactive and reactive tools'],
    kpis: ['Agent productivity', 'CSAT scores', 'Operational efficiencies', 'Business user productivity', 'Travel costs', 'Manual effort'],
    bestPractices: [
      'Monitor systems for potential issues before they impact users.',
      'Minimize disruptions through predictive maintenance.',
      'Leverage advanced analytics and ML to become more agile and efficient.',
      'Use remote diagnostic/control tools to streamline reactive support.',
    ],
    thingsToConsider: [
      'Have you developed a process for using automated scripts to remediate common issues?',
      'Do you have proactive scripts that integrate user interaction to resolve predefined issues?',
      'Have you established integrated proactive monitoring and management tools?',
      'Do you enforce the security of remote sessions by integrating RBAC?',
      'Do you have a solution for recording remote control sessions?',
    ],
    workshopScript: 'The best support experience is the one the user never has to request. Proactive support catches issues before they become tickets. And when intervention is needed, remote support eliminates the need for desk visits. Let\'s explore your current capabilities.',
    conversationStarters: [
      'Can your support team resolve issues on a user\'s device without them being physically present?',
      'Do you have automated scripts that fix common problems without any human intervention?',
      'How do you ensure remote support sessions are secure, auditable, and compliant?',
    ],
    discoveryQuestions: [
      'What percentage of support issues are resolved proactively vs. reactively?',
      'Do you have automated remediation scripts for common device issues?',
      'Are your remote support sessions logged and auditable for compliance?',
      'Can your tools proactively monitor endpoint health and trigger remediation?',
      'How much does physical desk-side support cost you compared to remote resolution?',
    ],
  },
  {
    id: 'dependency-service-mapping',
    name: 'Dependency & Service Mapping',
    domain: 'endpoint',
    description: 'Scanning, classification, and identification of networks loaded into the CMDB. Visualize relationships and connectivity points across infrastructure showing application and service dependency mapping.',
    features: ['Network, CI and Cloud Discovery', 'Agentless scanning', 'Dependency mapping', 'Enhanced real-time visibility', 'Improved root cause identification'],
    kpis: ['CSAT', 'CMDB efficiency', 'Actionable insights', 'Security compliance', 'Downtime', 'Unknown endpoints'],
    bestPractices: [
      'Schedule regular automated scans to maintain up-to-date maps.',
      'Leverage visualization for clear insights and seamless integration with ITSM and CMDBs.',
      'Implement real-time monitoring, strict access controls, and continuous process improvements.',
      'Use dependency mapping for strategic planning and align with industry standards.',
    ],
    thingsToConsider: [
      'Do you know what services are impacted by an outage before your end users do?',
      'Do you have a process for relationship mapping with servers, applications, and infrastructure?',
      'Is dependency and service mapping visibility used within your change and problem management processes?',
      'Is your service mapping integrated with process optimization?',
      'Do you frequently update your dependency map?',
    ],
    workshopScript: 'Service mapping is about understanding what connects to what. When a server goes down, do you instantly know which business services are affected? Or does someone start making phone calls? Let\'s explore your visibility.',
    conversationStarters: [
      'If your primary database server went down right now, could you immediately tell me which business services would be impacted?',
      'When you approve a change, do you have a visual dependency map showing the blast radius?',
      'How often do you discover "oh, THAT was connected to THAT?" during an outage?',
    ],
    discoveryQuestions: [
      'Can you visualize the dependencies between servers, applications, and business services?',
      'Is your service mapping data integrated with change and problem management?',
      'How often are your dependency maps refreshed — is it automated or manual?',
      'Do you use agentless scanning to discover infrastructure, or require agents on every device?',
      'When an outage occurs, how long does it take to identify the root cause and blast radius?',
    ],
  },
  {
    id: 'byod',
    name: 'Bring Your Own Device (BYOD) Management',
    domain: 'endpoint',
    description: 'Secure applications and data on personal devices while providing analytics and mobile threat defense. Segregate and control company data on the user\'s personal device.',
    features: ['Enforce acceptable use policies', 'Increase security in the everywhere workplace', 'Company/personal data segregation'],
    kpis: ['Device model compliance', 'Data security', 'Employee/agent productivity', 'User experience', 'Hardware expenses'],
    bestPractices: [
      'Establish clear policies for personal and corporate data, ensuring employee privacy and regulatory compliance.',
      'Implement real-time monitoring and mandate data encryption with the ability to remove company data from lost devices.',
      'Enforce company policies with employee transition/termination and lost device notification.',
      'Educate employees about data policies and processes.',
    ],
    thingsToConsider: [
      'Do you allow BYOD devices in your environment?',
      'Have you defined your BYOD policy and procedures?',
      'Do you have a defined BYOD support practice for various personal devices?',
      'Do you manage third-party applications on BYOD devices for security and compliance?',
    ],
    workshopScript: 'BYOD is a reality in most organizations. Employees expect to use their personal devices for work. The challenge is securing company data without invading personal privacy. Let\'s explore your approach.',
    conversationStarters: [
      'Do you allow personal devices to access company data — and if so, how do you secure that?',
      'If an employee\'s personal phone with company email is lost, can you wipe just the company data?',
      'How do you handle the tension between employee privacy and corporate security on personal devices?',
    ],
    discoveryQuestions: [
      'Do you have a formal BYOD policy, and is it enforced?',
      'Can you segregate company data from personal data on BYOD devices?',
      'What happens to company data on a personal device when an employee leaves?',
      'Do you manage third-party apps on BYOD devices for compliance?',
      'How do you provide support for the variety of personal device types your employees use?',
    ],
  },
  {
    id: 'mobile-field-device-security',
    name: 'Mobile & Field Device Security',
    domain: 'endpoint',
    description: 'Safeguard mobile devices that connect to enterprise networks from common threats. Ensure proper mobile security such as MFA to protect sensitive data.',
    features: ['Enforce policies to enhance security', 'Manage complete device lifecycle', 'Flexible app/device deployment', 'Reduce risk from lost devices', 'Enhance security and access to resources', 'Integrate new capabilities'],
    kpis: ['Device health and compliance', 'CSAT scores', 'Employee productivity', 'IT and organizational cost'],
    bestPractices: [
      'Implement comprehensive policies that include device encryption, strong authentication, and regular software updates.',
      'Employ centralized mobile management solutions to monitor, manage, and enforce security across all devices.',
      'Educate employees on security practices such as avoiding suspicious downloads and using secure networks.',
    ],
    thingsToConsider: [
      'Do you have an MDM solution in place today?',
      'Are you leveraging technologies to detect and prevent security threats on mobile devices?',
      'Do you manage access control and authentication for mobile devices, including MFA?',
      'Are you ensuring data segregation and encryption based on device ownership?',
      'Do you manage and secure applications on mobile devices?',
    ],
    workshopScript: 'Mobile devices are everywhere — and every one of them is a potential security risk. Phones are lost, stolen, and compromised. Let\'s assess how well your mobile security program protects the organization.',
    conversationStarters: [
      'When a mobile device is lost, how quickly can you detect it and take action?',
      'Are your mobile devices encrypted and enforcing MFA — every single one?',
      'How do you prevent sensitive corporate data from leaking through mobile apps?',
    ],
    discoveryQuestions: [
      'Do you have an MDM solution managing all corporate mobile devices?',
      'Are you using mobile threat defense to detect malware and phishing on mobile?',
      'Is MFA enforced on all mobile access to corporate resources?',
      'Can you remotely lock, wipe, or quarantine a compromised mobile device?',
      'How do you manage app security on mobile — whitelisting, blacklisting, or no control?',
    ],
  },
  {
    id: 'iot-iiot-access-security',
    name: 'Internet of Things / IIoT Access Security',
    domain: 'endpoint',
    description: 'Secure your enterprise estate focused on IoT and connected networks from threats and breaches. Identify, protect, and monitor risks while proactively fixing vulnerabilities.',
    features: ['Understand endpoints', 'Track and manage devices', 'Identify IT security voids', 'Patch and remediate', 'Risk-based strategy posture'],
    kpis: ['Patching cadence', 'Security compliance', 'Mean time to detect (MTTD)', 'Mean time to remediate (MTTR)', 'Unidentified devices/intrusion attempts', 'Security incidents'],
    bestPractices: [
      'Secure IoT endpoints by keeping them updated.',
      'Use encryption, automate security with antivirus software, and keep tabs on all connected devices.',
      'Regularly audit actions on your network and disable unused devices and entry points.',
    ],
    thingsToConsider: [
      'Have you modernized your network architecture to ensure IoT devices cannot cause disruption or breaches?',
      'Do you identify, document, and classify all IoT endpoints on your network?',
      'Are security policies enforced for IoT endpoints to mitigate risk?',
      'Do you have continuous monitoring and threat detection for IoT devices?',
      'Are measures taken for network segmentation and access control for IoT?',
      'Do you perform regular security assessments and audits of your IoT environment?',
    ],
    workshopScript: 'IoT is the invisible attack surface. Cameras, sensors, HVAC systems, badge readers — they\'re all connected, and most of them weren\'t designed with security in mind. Let\'s explore how visible and secured your IoT estate really is.',
    conversationStarters: [
      'Do you know exactly how many IoT devices are connected to your network right now?',
      'Are your IoT devices on a separate network segment from your corporate systems?',
      'When was the last time your security cameras or HVAC controllers were patched?',
    ],
    discoveryQuestions: [
      'Can you identify and classify all IoT devices on your network?',
      'Are IoT devices network-segmented from corporate resources?',
      'Do you enforce security policies on IoT endpoints?',
      'How do you patch IoT devices — many don\'t support traditional patching methods?',
      'Do you have continuous monitoring for anomalous IoT device behavior?',
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // EXPOSURE MANAGEMENT (4)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'rbvm',
    name: 'Risk Based Vulnerability Management (RBVM)',
    domain: 'exposure',
    description: 'Protect your organization from vulnerabilities that pose the greatest risk to better guard against data breaches, ransomware, and other cyber threats.',
    features: ['Enhanced device security', 'Threat intelligence', 'Analyze and prioritize risk', 'Resource optimization', 'Threat aggregation'],
    kpis: ['Organizational visibility', 'CSAT scores', 'Support agent bandwidth', 'Security and IT agility', 'Security compliance', 'Organizational risk'],
    bestPractices: [
      'Evolve your vulnerability management strategy by continuously correlating infrastructure with vulnerability data, threat intelligence, and pen test findings.',
      'Enable precise risk measurement, early warnings, attack prediction, and prioritized remediation.',
      'Enhance proactive defense mechanisms and ensure focused protection of critical assets.',
    ],
    thingsToConsider: [
      'Do you have insights into device vulnerability management across your enterprise?',
      'Are you tracking and assessing your ransomware exposure?',
      'Do you manage the risks associated with third-party vendors and their vulnerabilities?',
      'Do you schedule penetration testing exercises?',
      'Do you ensure that all assets are included in your vulnerability management scope?',
      'Do you integrate vulnerability management with your incident response plan?',
    ],
    workshopScript: 'Not all vulnerabilities are equal. Your team probably has thousands of CVEs in the backlog. The question isn\'t whether you have vulnerabilities — it\'s whether you\'re fixing the right ones first. Let\'s explore your prioritization approach.',
    conversationStarters: [
      'How many open vulnerabilities are in your backlog right now? Is that number growing or shrinking?',
      'How do you decide what to patch first — CVSS score, or something more contextual?',
      'Are you able to correlate vulnerabilities with active threat intelligence to know what\'s actually being exploited?',
    ],
    discoveryQuestions: [
      'How do you currently prioritize which vulnerabilities to remediate first?',
      'Do you have visibility into which vulnerabilities are actively being exploited in the wild?',
      'Is your vulnerability management integrated with your incident response plan?',
      'Do you include third-party and vendor vulnerabilities in your scope?',
      'How do you track your ransomware exposure specifically?',
    ],
  },
  {
    id: 'attack-surface-management',
    name: 'Attack Surface Management',
    domain: 'exposure',
    description: 'Proactively mitigate cyber threats with comprehensive visibility into external-facing assets. Continuously monitor internet-facing assets to uncover risk and vulnerabilities often missed by traditional tools.',
    features: ['Discovery of unknown external-facing assets', 'Full visibility of exposures on external-facing assets', 'Actionable intelligence on exposures', 'Risk assessments on partners and subsidiaries', 'Detect data leakage'],
    kpis: ['Percentage of known and managed assets', 'Efficient incident response', 'Operational costs', 'Compliance and regulatory adherence', 'Phishing and social engineering attacks', 'Shadow IT and cloud sprawl'],
    bestPractices: [
      'Regularly update your inventory of internet-facing assets.',
      'Use real-time monitoring tools with threat intelligence to identify suspicious activity.',
      'Address vulnerabilities and manage shadow IT through risk assessments.',
      'Undertake regular audits and employee training.',
    ],
    thingsToConsider: [
      'Do you maintain continuous visibility into your internet-facing assets, including shadow IT?',
      'Do you have a defined process for prioritizing risks related to your attack surface?',
      'Are you conducting risk assessments on subsidiaries, M&A, partners, and vendors?',
      'Is there automation in place for threat detection and response?',
      'Do you use threat intelligence feeds to assess risk prioritization?',
      'Do you conduct regular security audits on your external-facing assets?',
    ],
    workshopScript: 'Your attack surface is everything that faces the internet — and a lot of it you might not even know about. Shadow IT, forgotten test environments, cloud instances from an M&A. Let\'s understand what your external exposure looks like.',
    conversationStarters: [
      'If I scanned your organization\'s external attack surface right now, would you be surprised by what I found?',
      'Do you assess the security posture of partners and vendors before integrating their systems?',
      'How do you discover shadow IT — cloud services employees signed up for without IT approval?',
    ],
    discoveryQuestions: [
      'Do you have continuous visibility into all internet-facing assets, including shadow IT?',
      'Are you conducting third-party and supply chain risk assessments?',
      'How do you detect and manage cloud sprawl and unauthorized SaaS?',
      'Is your attack surface monitoring automated, or periodic manual assessments?',
      'Do you have a process for prioritizing which external exposures to address first?',
    ],
  },
  {
    id: 'patch-deployment-controls',
    name: 'Patch & Deployment Controls',
    domain: 'exposure',
    description: 'Ensure stability, security, and compliance by automating and simplifying the deployment of patches, vulnerability remediation, and application updates from a central location.',
    features: ['Risk mitigation', 'Improve compliance reporting', 'Centralized deployment', 'App and OS version control', 'Prioritization and evaluation of patches'],
    kpis: ['Employee productivity', 'Device health', 'Resource hours', 'Organizational risk', 'Manual activities', 'Network traffic'],
    bestPractices: [
      'Build, schedule, and test various remediation and OS patching cycles using scan–analyze–test–repair–scan methodology.',
      'Leverage release orchestration to coordinate automated and on-demand tasks.',
      'Plan deployment around maintenance windows and change management cycles.',
    ],
    thingsToConsider: [
      'Have you defined your various release policies (standard, emergency, and maintenance patches)?',
      'Do you have mechanisms to enhance governance and alignment in compliance reporting?',
      'Have you established scheduling of patch and deployment cycles with auto-deployments?',
      'Do you have the ability to patch third-party devices and applications?',
      'Do you have the ability to patch and deploy to various operating systems across all device types?',
    ],
    workshopScript: 'Patching is one of the most important things you do — and one of the most operationally painful. Let\'s talk about how your patching process works today: the cadence, the coverage, the automation level, and where things get stuck.',
    conversationStarters: [
      'Walk me through your patch cycle: how long from "patch released" to "deployed across the environment?"',
      'Can you patch third-party applications (Chrome, Adobe, Java), or only OS patches?',
      'When a zero-day is announced, what does your emergency patching process look like?',
    ],
    discoveryQuestions: [
      'Do you have defined release policies for standard, emergency, and maintenance patches?',
      'Is your patching automated with scheduling and zero-touch deployment?',
      'Can you patch across all OS types and third-party applications from a central location?',
      'How do you test patches before deploying to production?',
      'What\'s your average time from patch release to full deployment?',
    ],
  },
  {
    id: 'application-security-posture',
    name: 'Application Security Posture Management',
    domain: 'exposure',
    description: 'Enable fast, informed decisions to improve the security of applications through measures designed to protect applications from threats and vulnerabilities throughout the development lifecycle.',
    features: ['Visibility of application risk exposure and rating', 'Threat intelligence', 'Automated security testing', 'Diverse data sources', 'Customizable dashboards'],
    kpis: ['Number of vulnerabilities detected', 'Compliance audit pass rate', 'Mean time to detect (MTTD)', 'Mean time to remediate (MTTR)', 'Organizational risk', 'Security debt', 'Misconfigurations per deployment'],
    bestPractices: [
      'Constantly scan application assets throughout the development lifecycle for misconfigurations and vulnerabilities.',
      'Contextualize applications with internal and external vulnerability data and threat intelligence.',
      'Build custom dashboards for all security stakeholders.',
    ],
    thingsToConsider: [
      'Do you have native application development in your organization?',
      'Are you following best practices such as OWASP frameworks for secure coding?',
      'Do you prioritize, fix, and track issues throughout the software development lifecycle?',
      'Are you currently using a SAST/DAST/OSS scanner?',
      'Are you using any tool to prioritize vulnerabilities found?',
      'Do you periodically pentest your applications?',
    ],
    workshopScript: 'If your organization develops applications — internal or customer-facing — application security is part of your attack surface. Let\'s explore how security is integrated into your development lifecycle.',
    conversationStarters: [
      'Do you have internal application development, and if so, how is security integrated into the SDLC?',
      'Are you running SAST/DAST scans on your applications, and how often?',
      'How do your dev teams prioritize which application vulnerabilities to fix — severity, exploitability, or business impact?',
    ],
    discoveryQuestions: [
      'Do you develop applications in-house, and is security testing part of the development pipeline?',
      'Are you using SAST, DAST, or SCA tools to scan for application vulnerabilities?',
      'How do you prioritize application security findings — by severity or exploitability?',
      'Do you track security debt in your applications?',
      'Do you perform regular penetration testing on your applications?',
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // FOUNDATIONS (8)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'grc',
    name: 'Governance, Risk & Compliance (GRC)',
    domain: 'foundations',
    description: 'Strategies, processes, and tools that organizations employ to ensure they operate within legal boundaries, manage risks effectively, and adhere to established policies and standards.',
    features: ['Streamline compliance', 'Modernize risk assessment', 'Centralize documentation', 'Automate governance', 'Improve audit efficiency', 'Optimize resource allocation'],
    kpis: ['Business user productivity and retention', 'Security compliance and true-up cost', 'Visibility into GRC processes', 'Resource bandwidth', 'Support calls', 'Audit resource constraints', 'Risk of data and productivity loss'],
    bestPractices: [
      'Integrate governance frameworks to oversee decision-making.',
      'Adopt risk management practices to identify and mitigate threats, and measure compliance.',
      'Consolidate regulatory documentation and align requirements like HIPAA, SOX, and GDPR with security best practices.',
      'Foster clear communication and collaboration across departments.',
    ],
    thingsToConsider: [
      'Do you maintain regulatory documents and compliance controls in a single system?',
      'Do you automate your governance, risk, and compliance process?',
      'Are you tracking the impact of GRC incidents?',
      'Are your GRC activities and processes visible to all relevant stakeholders?',
      'Are you regularly updating and verifying your compliance posture?',
    ],
    workshopScript: 'GRC is the framework that keeps everything in bounds — legal, regulatory, policy. It\'s often seen as overhead, but done well, it\'s what prevents costly breaches, fines, and audit failures. Let\'s assess your GRC maturity.',
    conversationStarters: [
      'Is your compliance documentation centralized, or scattered across departments and SharePoint sites?',
      'How much time does your team spend preparing for audits — days, weeks, or months?',
      'Are you tracking the business impact of GRC incidents, or just logging them?',
    ],
    discoveryQuestions: [
      'Do you have a centralized system for regulatory documents and compliance controls?',
      'How automated is your GRC process — manual spreadsheets or integrated tools?',
      'How long does audit preparation take, and how many people are involved?',
      'Are all relevant stakeholders able to see GRC activities and compliance status?',
      'How do you handle multi-framework compliance (HIPAA, SOX, GDPR, PCI)?',
    ],
  },
  {
    id: 'data-management',
    name: 'Data Management',
    domain: 'foundations',
    description: 'Collecting, organizing, protecting, and storing an organization\'s data. With effective data management, people can find and access trusted data for their queries.',
    features: ['Governance framework', 'Normalization', 'Integrity', 'Availability', 'Quality assurance', 'Confidentiality'],
    kpis: ['Data hygiene', 'Security', 'Scalability', 'Access and retrieval time', 'Organizational risk', 'Duplication and redundancy'],
    bestPractices: [
      'Implement a process to improve the quality of your data.',
      'Schedule audits for accuracy so data does not become stale.',
      'Data should be accessible with the correct level of access.',
      'Verify that processes meet compliance requirements. Train teams to properly handle data.',
      'Be prepared for worst-case scenarios with a strategy for potential breaches or integrity issues.',
    ],
    thingsToConsider: [
      'Do you currently have a data governance framework in place?',
      'Are there clear data ownership roles defined within your organization?',
      'Do you have mechanisms to ensure the integrity of your data throughout its lifecycle?',
      'Is there a disaster recovery plan in place for data loss scenarios?',
      'Do you have data retention policies for outdated or redundant data?',
    ],
    workshopScript: 'Data is the foundation of every decision your IT organization makes. If your data is duplicated, stale, or inaccurate, every tool and process built on top of it suffers. Let\'s check the health of your data management practices.',
    conversationStarters: [
      'If two people in your organization pulled the same report from different sources, would they get the same answer?',
      'Who owns data quality in your organization — is there a defined owner, or is it assumed?',
      'When was the last time you audited your data for accuracy and removed stale records?',
    ],
    discoveryQuestions: [
      'Do you have a formal data governance framework with defined ownership roles?',
      'How do you ensure data integrity across its lifecycle — from creation to archival?',
      'Is there a disaster recovery plan specifically for data loss?',
      'Do you have data retention and cleanup policies for redundant or outdated data?',
      'How do you handle data normalization across multiple source systems?',
    ],
  },
  {
    id: 'continual-improvement',
    name: 'Continual Improvement & Process Optimization',
    domain: 'foundations',
    description: 'Continuously review processes, products, and services to drive incremental and step-change operational improvements.',
    features: ['Enhance collaboration across the organization', 'Streamline business processes', 'Improve roadmap visibility', 'Data-driven insights'],
    kpis: ['Agent productivity', 'Operational efficiencies', 'Process maturity', 'CSAT scores', 'IT confidence', 'Cross-organizational partnership', 'Operational costs'],
    bestPractices: [
      'Create a structured framework to streamline ongoing delivery improvements.',
      'Keep initiatives aligned and on track while powering better decisions and breaking down silos.',
      'Develop feedback mechanisms to capture areas for improvement.',
    ],
    thingsToConsider: [
      'Is there a process to identify pain points and opportunities for improvement?',
      'Do you have a recurring meeting cadence to review operational procedures?',
      'Do you leverage a methodology for continual improvement? (Agile, Lean, Six Sigma, etc.)',
      'Do your organization/department goals incorporate continual improvement?',
      'Do you have buy-in at an executive level for continual improvement?',
    ],
    workshopScript: 'Continual improvement is what separates organizations that get better over time from those that stay stuck. It\'s about building a culture and process for identifying what\'s not working and fixing it systematically.',
    conversationStarters: [
      'When was the last time your team formally reviewed a process and made it better?',
      'Do you use any improvement methodology — Lean, Six Sigma, Agile, or even informal retrospectives?',
      'How do front-line employees share improvement ideas with leadership?',
    ],
    discoveryQuestions: [
      'Do you have a formal process for identifying and implementing process improvements?',
      'Is there a recurring cadence for reviewing operational procedures and high-volume tasks?',
      'Do you use a specific methodology (Agile, Lean, Six Sigma, Kaizen)?',
      'Do department goals include continual improvement objectives?',
      'Is there executive sponsorship for continual improvement initiatives?',
    ],
  },
  {
    id: 'business-continuity',
    name: 'Business Continuity',
    domain: 'foundations',
    description: 'An organization\'s ability to continue operations and delivery of products or services at acceptable levels following unintended disruptive events.',
    features: ['Integrate risk and service management', 'Operationalize disaster recovery and crisis management', 'Consolidate planning data', 'Identify business critical systems and data'],
    kpis: ['User experience', 'Organizational visibility', 'Business agility', 'Organizational risk'],
    bestPractices: [
      'Establish and maintain a detailed business continuity plan integrated with service management.',
      'Regularly test and update the plan through simulations and reviews.',
      'Continuously monitor and improve strategies based on performance metrics and feedback.',
    ],
    thingsToConsider: [
      'Do you have a modernized network architecture to ensure business continuity?',
      'Have you developed a unified BC/DR plan aligned with risk management frameworks?',
      'Do you have robust procedures in your DR and crisis management plans, and are they tested often?',
      'Have you identified your priority one systems in case of a DR event?',
      'Do you have a process to ensure business critical data is in sync and available?',
    ],
    workshopScript: 'Business continuity planning is insurance you hope you never need — but when you do, it\'s everything. Let\'s explore how prepared your organization is for disruptions, whether it\'s a ransomware attack, a data center failure, or a natural disaster.',
    conversationStarters: [
      'When was the last time you tested your disaster recovery plan — and what did you learn?',
      'Can you identify, right now, your top 5 priority-one systems that must stay running no matter what?',
      'If your primary data center went offline today, how long until operations resume at an acceptable level?',
    ],
    discoveryQuestions: [
      'Do you have a documented and tested business continuity / disaster recovery plan?',
      'Have you identified your priority-one systems and data?',
      'How often do you run BC/DR simulations or tabletop exercises?',
      'Is your BC plan integrated with your service management and risk frameworks?',
      'Do you have a process ensuring critical data is replicated and available for recovery?',
    ],
  },
  {
    id: 'network-discovery',
    name: 'Network Discovery',
    domain: 'foundations',
    description: 'Active and passive scanning to discover network devices. Active scanning probes the network; passive scanning listens for new connections on the subnet.',
    features: ['Use active and/or passive scanning', 'Minimize bandwidth consumption', 'Uses horizontal and top-down discovery', 'Populate CIs using network probes', 'Enhance CI insights'],
    kpis: ['Operational efficiencies', 'Security compliance', 'Actionable insights', 'Service availability', 'Time to value', 'Unknown endpoints', 'Security risk'],
    bestPractices: [
      'Orchestrate active and passive scanning to balance visibility with minimizing user disruption.',
      'Identify unauthorized devices and unusual activity.',
      'Use various techniques to map network topology, understand configurations, and monitor status.',
    ],
    thingsToConsider: [
      'Do you accurately discover what is connected to your network?',
      'Do you have devices listening for new connections to your network?',
      'Are your scans scheduled to run regularly with minimal impact on bandwidth?',
      'Are existing CMDB and CI records updated to reflect scan results?',
      'Do you use the right credentials for scans to obtain maximum information?',
    ],
    workshopScript: 'You can\'t manage or secure what you can\'t see. Network discovery is the starting point for visibility into your entire environment. Let\'s assess how complete and current your discovery process is.',
    conversationStarters: [
      'How confident are you that you know every device connected to your network right now?',
      'Do your discovery scans run on a regular schedule, or only when someone triggers them manually?',
      'When was the last time a discovery scan revealed a device nobody knew about?',
    ],
    discoveryQuestions: [
      'Do you use active scanning, passive scanning, or both?',
      'Are your discovery scans scheduled to run regularly with minimal bandwidth impact?',
      'Do scan results automatically update your CMDB and CI records?',
      'Do you have the correct credentials configured to get maximum detail from scans?',
      'How do you handle unauthorized devices discovered on the network?',
    ],
  },
  {
    id: 'third-party-connectors',
    name: 'Third Party Connectors, APIs & Integrations',
    domain: 'foundations',
    description: 'Use certified integrations and discovery methods to ingest third-party data, ensuring timeliness, integrity, and real-time visibility across diverse platforms.',
    features: ['Confidently ingest 3rd party data', 'Keep pace with dynamic multi-cloud environments', 'Leverage integrations across your IT landscape', 'Normalize and consolidate 3rd party data'],
    kpis: ['Incident deflection', 'Scalability', 'Actionable insights', 'Time to value', 'Security compliance', 'Multi-cloud strategy delivery'],
    bestPractices: [
      'Where possible, utilize existing APIs and connectors to transport data between systems.',
      'Leverage technologies across multiple solutions to create workflow efficiencies.',
      'Reduce manual tasks and create positive user experiences through integration.',
    ],
    thingsToConsider: [
      'Is your 3rd party data trusted and secure?',
      'Do you leverage 3rd party data to fill gaps that would otherwise require manual tasks?',
      'Do you implement APIs and integrations for shared data across disparate systems?',
      'Are you continually reviewing opportunities to leverage APIs to create new value?',
      'Do you have an API and integration policy or governance framework to reduce risk?',
    ],
    workshopScript: 'No tool operates in a vacuum. The value of your IT ecosystem depends on how well your tools talk to each other. Let\'s explore your integration strategy and where data silos still exist.',
    conversationStarters: [
      'How many of your IT tools are integrated with each other vs. operating in silos?',
      'When you need data from a third-party tool, is it a one-click integration or a manual export/import?',
      'Do you have an API governance framework, or does each team integrate on their own?',
    ],
    discoveryQuestions: [
      'How many third-party integrations do you currently maintain?',
      'Is third-party data normalized and consolidated, or raw and inconsistent?',
      'Do you have a governance framework for API usage and integration security?',
      'How do you keep integrations current with vendor API changes?',
      'Are you leveraging integrations to automate workflows, or just for data sharing?',
    ],
  },
  {
    id: 'cmdb',
    name: 'Configuration Management Database (CMDB)',
    domain: 'foundations',
    description: 'Centralize all configuration information including critical CIs and associated relationships into a managed configuration. Enable better business decisions with accurate information.',
    features: ['Improved IT estate lifecycle management', 'Achieve data-driven outcomes', 'Establish single source of truth', 'Enhanced reporting and analytics', 'Improved change management'],
    kpis: ['Awareness and actionability', 'Visibility', 'Service quality', 'Operational efficiencies', 'Manual effort'],
    bestPractices: [
      'Automate CI information to populate your CMDB and integrate with other IT management tools.',
      'Define clear processes for change management to ensure stakeholders are involved in managing the CMDB.',
    ],
    thingsToConsider: [
      'Is your CMDB up-to-date and accurate based on your discovery methods?',
      'Do you have gaps in your discovery process?',
      'Are you manually adding non-discoverable assets?',
      'Are you able to scale your CMDB to meet future needs?',
      'Have you defined what components you want to manage in your CMDB?',
    ],
    workshopScript: 'The CMDB is the single source of truth for your IT environment. When it\'s accurate, everything downstream — change management, incident resolution, security — works better. When it\'s stale, everything suffers. Let\'s assess the health of your CMDB.',
    conversationStarters: [
      'On a scale of 1-10, how much do you trust the data in your CMDB right now?',
      'Is your CMDB populated automatically through discovery, or does someone manually update it?',
      'When was the last time you found a significant gap in your CMDB — something missing that should have been there?',
    ],
    discoveryQuestions: [
      'Is your CMDB automated through discovery, or manually maintained?',
      'How accurate would you estimate your CMDB data is right now?',
      'Are you managing non-discoverable assets (cloud, SaaS, virtual) in the CMDB?',
      'Is your CMDB integrated with change management and incident management?',
      'Can your CMDB scale to accommodate growth — cloud, multi-cloud, containers?',
    ],
  },
  {
    id: 'reporting',
    name: 'Reporting',
    domain: 'foundations',
    description: 'Surface analytics on-demand to drive actionable insights. Take action with the latest data through customized reports and the ability to connect to other databases.',
    features: ['Immediate access to data', 'Enhanced data visibility and integrity', 'Improved data security through insights'],
    kpis: ['Data-driven actions', 'Operational efficiencies', 'Visibility', 'Manual effort'],
    bestPractices: [
      'Leverage insights with the latest data to increase awareness and actionability.',
      'Transform from reactive to proactive with customized data sets across your organization.',
      'Enable field teams to create and run reports without IT assistance.',
    ],
    thingsToConsider: [
      'Do you develop on-demand self-service dashboards versus weekly automated Excel reports?',
      'Do you measure how much time is spent on creating reports and dashboards?',
      'Have you built an intake process for business users to request reports?',
      'Do you leverage reporting tools with advanced visualization capabilities beyond spreadsheets?',
      'When you create reports, is the data current and error-free?',
    ],
    workshopScript: 'Reporting is how IT demonstrates value to the business. If your reports are manual, delayed, or hard to access, leadership can\'t make informed decisions. Let\'s explore how mature your reporting capabilities are.',
    conversationStarters: [
      'When leadership asks for a report on IT performance, how long does it take to produce?',
      'Are your reports real-time dashboards, or weekly Excel files someone compiles manually?',
      'Can your business users self-serve reports, or do they always need to request them from IT?',
    ],
    discoveryQuestions: [
      'Are your reports on-demand dashboards or scheduled static exports?',
      'How much time per week is spent creating and maintaining reports?',
      'Can business users create their own reports without IT involvement?',
      'Do you use advanced visualization tools, or primarily spreadsheets?',
      'Is the data in your reports current and accurate, or is there a lag?',
    ],
  },
];

export function getCapabilityById(id: string): CapabilityCard | undefined {
  return capabilities.find(c => c.id === id);
}

export function getCapabilitiesByDomain(domain: Domain): CapabilityCard[] {
  return capabilities.filter(c => c.domain === domain);
}
